### ISSUE TITLE
make FNodes and walkers easier to use

### ISSUE THREAD

**Issue by agriggio** [pysmt/pysmt#102]
It seems that FNodes have a lot of hardcoded information, that makes
using them somewhat inconvenient. For instance, I could not understand
how to retrieve the sort of a node in a generic way, without using big
"switch statements" over the node types (which are tedious and will
break as soon as some other node types are added). For symbols, there's
`FNode.symbol_type()`, but what about other nodes? For example, how do I
know that an `AND` is of Bool sort without knowing that it is an `AND`
operator?

Related to this, the use of walkers seems also quite verbose. From what
I understand, one needs to implement the various `walk_*` functions for
all the different nodes, because examining the `node_type()` is the only
way of retrieving all the information needed to properly operate on
formulas.

For a concrete example, I was trying to implement a walker to extract
all the atoms in the formula. I was trying to do something like this:

```
class GetAtomsWalker(pysmt.walkers.dag.DagWalker):
    def __init__(self):
        super(ImplicantWalker, self).__init__()
        for k in self.functions:
            self.functions[k] = self.walk_get_atom
        self.atoms = []

    def walk_get_atom(self, formula, **kwargs):
        if formula.is_quantifier():
            raise NotImplementedError("get_atoms for quantified formulae")
        
        if formula.symbol_type().is_bool_type():
            if not formula.is_boolean_operator():
                self.atoms.append(formula)
```

But this does not work, because `formula.symbol_type()` only works if
`formula.is_symbol()` is true, otherwise it fails (horribly :-)

**Comment by marcogario** [comment]
For the first point, is using the operator groups in pysmt.operators enough for your need? Do you think it would be better to implement them in the FNode. E.g., FNode.is_bool_op() ? The implementation would simply embed the current approach:
```
def is_bool_op(self):
  return self.node_type() in operators.BOOL_OPERATORS
```

For what concerns the Walkers. The idea is exactly to set the functions map in order to group together nodes that need to be handled in the same way. Having solved the issue above, do you still see problems with this approach?

Thanks for the feedback!

**Comment by agriggio** [comment]
Operator groups certainly help, but they still don't solve the original
issue, that is how do I retrieve the sort of a node without explicitly
checking what is its `node_type`. Maybe you could consider adding a
method `FNode.get_sort()`, that would do something like this:

```
def get_sort(self):
    if not self.is_term():
        raise Exception("not a term")
    if self.is_bool_op():
        return BOOL
    elif self.is_int_constant():
        return INT
    ...
    elif self.is_symbol():
        return self.symbol_type()
    ...
```

**Comment by agriggio** [comment]
Regarding the use of walkers, maybe you can add a method `set_default`
to set the default walk function? It seems cleaner than traversing the
functions dictionary directly

**Comment by mikand** [comment]
We thought about this issue. We think that a convenience function like
```python
self.set_function(self.walk_simple_args, DEPENDENCIES_SIMPLE_ARGS)
self.set_function(self.walk_quantifier, op.QUANTIFIERS)
self.set_function(self.walk_and, op.AND)
```
could be a good solution to hid the underlying functions map.

This seems clearer than a ```set_default``` function, as ```set_default = lambda x : set_function(x, op.ALL_TYPES)```...

**Comment by mikand** [comment]
For the typing issue see #116

**Comment by agriggio** [comment]
One more thing: it seems there is some non-determinism in building FNodes. I'm not sure where this comes from, but IMHO it would be important to avoid this.

**Comment by mikand** [comment]
I think this is probably related to #113 ...

**Comment by marcogario** [comment]
This issue has been broken into #116 and #113.

PR #139 closes the issue on defining functions in walkers.
