### ISSUE TITLE
Provide support for getting the return type of a node

### ISSUE THREAD

**Issue by mikand** [pysmt/pysmt#116]
We shall provide support for a member function that returns the expected type of an FNode (without type-checking):
```python
def get_sort(self):
    if not self.is_term():
        raise Exception("not a term")
    if self.is_bool_op():
        return BOOL
    elif self.is_int_constant():
        return INT
    ...
    elif self.is_symbol():
        return self.symbol_type()
    ...
```

**Comment by marcogario** [comment]
Why can't we use the type-checker for this?
It seems like the method get_sort, might be interesting for the operators, but not for the FNode. The Information on the type of the node is already checked (and memoized) at construction. Redoing it here seems a repetition.

Moreover, we need to solve the usual INT/REAL problem. This would either:
- Require a call to the type-checker
- Recur on the children
- Enforce the addition of one bit of information at construction time of the theory nodes

**Comment by marcogario** [comment]
I pushed a branch get_sort with an example of implementation of get_sort. Note that I also added a function get_type. The main difference is whether we rely on the Type-Checker or not.

The problem described above remains.

**Comment by marcogario** [comment]
Addressed by adding FNode.get_type() that performs a call to the type-checker. Notice that the type-checker has already the result memoized, therefore the call is rather cheap.

PR #143
