### ISSUE TITLE
Improve error message when solvers encounter an unsupported formula

### ISSUE THREAD

**Issue by mikand** [pysmt/pysmt#128]
Consider the following example:
```python
f = Equals(BVAnd(BV(1,3), BV(2, 3)), BV(0, 3))

with Solver(name="z3") as s:
    s.add_assertion(f)
    assert s.solve()
```

The code seems OK, but yields a very confusing error because Z3 does not support the BV theory (yet):
```
NotImplementedError: Was not expecting a node of type 20
```

We shall provide a more informative error when an unsupported formula is passed to a converter

**Comment by mikand** [comment]
This is related to #80

**Comment by marcogario** [comment]
PR #130
