### ISSUE TITLE
Overload infix notation for BitVectors and EUF

### ISSUE THREAD

**Issue by mikand** [pysmt/pysmt#129]
Currently, infix notation is supported (although discouraged) for LIRA.
We shall overload and extend it for BV and EUF:
```python
r * 3 # yields a real is r is real, if r is a bitvector it shall return a bitvector
f(3) #if f is a function symbol, this should return the application of 3 to f
```

**Comment by marcogario** [comment]
For BV see #229 . For UF, I am not sure how we want to proceed, and I think there is no particular need of doing this now.

**Comment by mikand** [comment]
Shall we open a dedicated issue and close this one?

**Comment by marcogario** [comment]
This addresses only BVs. Closing and opening a new one for UF.
