### ISSUE TITLE
FNode.is_one has unclear semantics

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#138]
FNode.is_one checks whether the node is a REAL constant of value 1. This means that:

```
>> Int(1).is_one()
False
```

I see the following options:
- Deprecate the function
- rename it to is_real_one
- overload the semantics so that it returns true if the node is either Int(1) or Real(1); false otherwise.

Same problem is for is_zero.

**Comment by mikand** [comment]
I would go for either deprecation or the overloaded semantics

**Comment by marcogario** [comment]
Going for overloaded semantics.

**Comment by marcogario** [comment]
PR #141
