### ISSUE TITLE
Extend quantifier eliminator interface to support logic specification

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#16]
Currently, we assume that a quantifier eliminator is capable of quantifying UFLIRA. 
A better approach would be to specify the logic as we do for solvers. This would also make it possible to integrate CUDD as Quantifier eliminator for BOOL.

**Comment by mikand** [comment]
We decided to implement this feature: at the moment we have LIA, LRA or BOOL.

Same criterion of the ```Solver``` shortcut will be used
