### ISSUE TITLE
Unify node types for constants

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#192]
We currently have a node type for each type of constant (e.g, ```REAL_CONSTANT```). This is not particularly useful, since the same information could be embedded in the constant itself and, for the BV and Enum, we actually need to provide additional information in the constant type.

The idea is to merge all Theory constant types into a single ```CONSTANT``` node-type. We do not want to mix boolean and Theory, but instead of defining a ```BOOL_CONSTANT``` node-type we will define a ```TRUE``` and ```FALSE``` node.

Any theory constant will have a payload containint the value and the type.

This change might break external code. therefore we will include it in version 0.5 .

**Comment by marcogario** [comment]
@mikand : we need to re-discuss this. I think now that different operators for different constants types is a good thing. Having different node types simplifies walking. A naive example is printing. Merging all constants into one, means that ``walk_constant``` would have to do a split by cases inside the function...

I do not see a real gain. I propose to close this as wontfix.

**Comment by mikand** [comment]
Agreed on wontfix
