### ISSUE TITLE
install.py: Refactoring

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#198]
install.py needs to be refactored, because it is not manageable, if we want to extend to more platforms.

In particular, we should have a main class: ```SolverInstaller``` that deals with the main flow of installation:

- Download
- Unpack
- (Optionally) Compile
- Create PYTHONPATH

Each Solver Installer would be a subclass of the above, in order to provide specific info like:

- Where to download from (taking into account platform etc)
- How to compile
- How to create the PYTHONPATH

Additionally, it would be nice if the download function was a bit smarter, and it attempted first to use the mirror and then connect to the original URL in case of failure.

**Comment by marcogario** [comment]
Additionally, install.py should provide a way to obtain the necessary pythonpath information, so that we can do:
```
$ ./install.py --env --z3
export PYTHONPATH=$PYTHONPATH:/..../

$ `./install.py --env --z3`
```

**Comment by marcogario** [comment]
The current version of install.py does not handle errors in the commands properly. E.g., it is quite common that the compilation failed but install.py thinks everything is ok. The new version should handle this properly.

**Comment by mikand** [comment]
PR #209
