### ISSUE TITLE
Handle Logic as string in shortcuts/factory 

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#220]
In some cases it would be easier to pass a string with the name of the logic to shortcuts method. 

If we so so, currently, we get that no solver for the logic exists. This is misleading. 

@agriggio suggests to handle strings automatically.

**Comment by marcogario** [comment]
I think that this mostly relates to ```Solver```, since shortcuts have automated logic selection. Nevertheless, i think that whatever decision we take should be applied uniformly.

**Comment by mikand** [comment]
Agreed, we may pass the logic specified by the user in a function that checks whether it is a logic object or a string for all the top-level functions in pysmt.

**Comment by marcogario** [comment]
The method for this exists and is ```pysmt.logics.get_logic```. My suggestion, would be to have a decorator for this ```@logic_as_string```, that checks if a type is string, and if so calls ```get_logic```.

I'd avoid requiring that the object is either a string or a logic, it seems over-constraining.

**Comment by marcogario** [comment]
```
def accept_logic_as_string(f):
    """Converts a logic provided as a string into a pysmt.logic object."""

    @wraps(f)
    def accept_logic_as_string_wrap(*args, **kwargs):
        logic = kwargs['logic']
        if logic is not None and type(logic) == str:
            logic = pysmt.logics.get_logic_by_name(logic)
            kwargs['logic'] = logic
        return f(*args, **kwargs)
    return accept_logic_as_string_wrap
```

This was the decorator that I had in mind. However, this requires that (if given) the logic is given as a keyword argument. I think this is a safe assumption, but it seems more complex than necessary.

**Comment by marcogario** [comment]
See #223 .

**Comment by agriggio** [comment]
Hmmm, this seems suboptimal... Now you would get a different
behaviour depending on whether you use keyword or positional
arguments. Also, what if the logic is a unicode object? How about this
version instead (untested, of course :^)?

```python
def accept_logic_as_string(f, pos=None):
    """Converts a logic provided as a string into a pysmt.logic object.
If pos is not None, it indicates the position of the logic argument in *args.
    """
    assert pos is None or pos >= 0

    @wraps(f)
    def accept_logic_as_string_wrap(*args, **kwargs):
        if pos is not None and pos < len(args):
            logic = args[pos]
        else:
            logic = kwargs.get('logic')
        if logic is not None:
            try:
                logic = pysmt.logics.get_logic_by_name(logic)
            except pysmt.logics.UndefinedLogicError:
                pass
            if pos is not None and pos < len(args):
                args = args[:pos] + (logic,) + args[pos+1:]
            else:
                kwargs['logic'] = logic
        return f(*args, **kwargs)
    return accept_logic_as_string_wrap
```

**Comment by marcogario** [comment]
Thanks for pointing the unicode issue out. Indeed, I missed that (and need to update the code and tests accordingly).

Eventually, I thought that the decorator was more complex than necessary. See PR #223 , there is actually only one point in the Factory class where we need to make such a conversion, the ```_get_solver_class``` method.
