### ISSUE TITLE
Enable infix notation when importing shortcuts

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#228]
Infix notation should not be used for writing "good" code, e.g., code within pySMT itself. It is unclear which environment you are using, makes a lot of intermediate calls etc, etc.

However, for many use cases, the infix notation makes the life of the user easier. I think this goes in the direction of the shortcuts module.

*Proposal*: Automatically enable infix notation when shortcuts is imported. In this way, all modules within pySMT will not be affected (since we do not import shortcuts), but small scripts will benefit from it, without the need of expliciting setting it.

**Comment by marcogario** [comment]
@mikand what do you think about this?

**Comment by mikand** [comment]
I do not have a strong point. As you know I do not like infix notation, but I guess I'm a minority...
OK for enabling it by default as long as we can still disable it.

**Comment by marcogario** [comment]
Yes, that is why I think this solution is a good compromise. It still
forces you to use non-infix operators within the library; you can continue
your own style outside of the library and, if you really want, infix is
available out of the box.

Ok, i'll open a pr with this.

**Comment by marcogario** [comment]
Fixed in #267.
