### ISSUE TITLE
Does PySMT support the recent floating point theory?

### ISSUE THREAD

**Issue by zell08v** [pysmt/pysmt#231]
Hello, 

FP theory has been added to SMT-LIB for a while. Does PySMT support it? I need to parse an SMT-Lib file like this:

(set-logic QF_FP)
(set-info :source |SPARK inspired floating point problems by Florian Schanda and Martin Brain|)
(set-info :smt-lib-version 2.0)
(set-info :category crafted)
(set-info :status sat)
(define-fun is_finite ((f Float32)) Bool (or (fp.isNormal f) (fp.isZero f) (fp.isSubnormal f)))
(define-fun f0 () Float32 ((_ to_fp 8 24) #x00000000))
(declare-fun a () Float32)
(declare-fun b () Float32)
(assert (is_finite a))
(assert (is_finite b))
(assert (fp.gt a f0))
(assert (fp.gt b f0))
(assert (not (fp.gt (fp.mul RNE a b) f0)))
(check-sat)
(exit)

Is that possible to do this using pysmt? Thanks.

**Comment by mikand** [comment]
Hi @zell08v ,

short answer is no, currently we have no support for FP.

Technically, it is possible to extend PySMT to do so, here is a short list of the needed changes for reference.

* Add the FP types to types.py
* Add relevant node types in operators.py
* Add operators constructors in formula.py
* Extend the basic walkers in walkers package
* Extend the parser
(* Add support to some solvers wrappers e.g. MathSAT)

If you are interested in helping on this issue we can surely provide support.
