### ISSUE TITLE
CVC4 and LIA

### ISSUE THREAD

**Issue by 2sev** [pysmt/pysmt#233]
When I try to use PySMT for LIA formulas with CVC4 as an underlying solver, it throws an exception: "pysmt.exceptions.NoSolverAvailableError: Solver 'cvc4' does not support logic LIA". Is this a correct behavior? I believe CVC4 does support LIA and it actually won the LIA category in the last SMTCOMP (http://smtcomp.sourceforge.net/2015/results-LIA.shtml?v=1446209369). Or maybe I am missing something. Could you please clarify if this is a bug? Thank you.

**Comment by mikand** [comment]
Hi @2sev,

in the current implementation of the CVC4 wrapper within pysmt, we do not support quantifiers. For this reason, pysmt reports the NoSolverAvailableError.

I do not know if the support of quantifiers over integer variables is complete within CVC4 (if you have info, please share), but the behavior you experience is the expected one in pysmt at this stage.

However, you can create a solver for the quantifier-free fragment of LIA:
```python
s = Solver(name='cvc4', logic=QF_LIA)
```

Actually, we started implementing the quantifier support for CVC4, but it is currently disabled in the automatic solver selection. You can work around this by building an instance of the CVC4 solver
```python
s = Solver(name='cvc4')
```
and then use it by asserting quantified formulae, normally. Note that this is still under development, if you encounter problems or have further questions, please do not hesitate to report here (or in another issue).

**Comment by 2sev** [comment]
Hi @mikand,

Thanks for the quick response. I am not an expert in SMT solving and so I can't be sure about this. But I believe CVC4 should be able to work with LIA formulas perfectly. The reason of my guess is that CVC4 won the corresponding category in the latest competition. Note that even the stable version of the solver participated in the competition (not only the experimental one). So the stable version should also support LIA.

However, since the version of CVC4 installable in pysmt is quite old (68f22235a62f5276b206e9a6692a85001beb8d42 is more than one year old) it is not clear for me if it supports LIA.

Thank you for suggesting a possible solution for the issue. I am going to try that. I will keep you informed if I have any problem with this workaround.

**Comment by 2sev** [comment]
Hi @mikand,

I tried the workaround you suggested previously. However, it does not work. I created a solver with `s = Solver(name='cvc4')` and then tried to call `s.is_sat(ForAll(f.get_free_variables(), f))` and got the following 

```
Traceback (most recent call last):
  File "/home/aign/test.py", line 92, in <module>
    msa = test_solver.solve()
  File "/home/aign/test.py", line 125, in solve
    print s.is_sat(ForAll(f.get_free_variables(), f))
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/solvers/solver.py", line 71, in is_sat
    self.add_assertion(formula)
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/solvers/cvc4.py", line 71, in add_assertion
    term = self.converter.convert(formula)
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/decorators.py", line 84, in catch_conversion_error_wrap
    res = f(*args, **kwargs)
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/solvers/cvc4.py", line 188, in convert
    return self.walk(formula)
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/walkers/dag.py", line 106, in walk
    res = self.iter_walk(formula, **kwargs)
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/walkers/dag.py", line 98, in iter_walk
    self._process_stack(**kwargs)
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/walkers/dag.py", line 91, in _process_stack
    self._compute_node_result(formula, **kwargs)
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/walkers/dag.py", line 75, in _compute_node_result
    self.memoization[key] = f(formula, args=args, **kwargs)
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/solvers/cvc4.py", line 241, in walk_forall
    self._rename_bound_variables(args[0], formula.quantifier_vars())
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/solvers/cvc4.py", line 386, in _rename_bound_variables
    old_var_list = [self.walk_symbol(x, []) for x in variables]
TypeError: walk_symbol() takes exactly 2 arguments (3 given)```

**Comment by mikand** [comment]
Hi,

indeed that is a bug.

I opened a branch with a fix (https://github.com/pysmt/pysmt/tree/cvc4-quantifiers) where I also enabled quantifiers in CVC4. I wrote some minimal tests (commit f9ba4b54b97c04adec7375e47f74128b743753a4).

Feel free to try this code, but it seems that CVC4 (at least the version I installed) returns "unknown" ever for very simple quantified formulae.

Note:
you have to specify the correct logic when you use quantifiers, otherwise CVC4 raises an exeption:
```python
with Solver(name='cvc4', logic=LIA) as s:
    ....
```

**Comment by 2sev** [comment]
Hi @mikand,

Thank you! I tried this. As you said, CVC4 almost always returns "unknown". Even for the simplest formulas. This is very strange. It probably makes sense for me to try the up-to-date version of CVC4 instead of the old one installed by pysmt.

**Comment by 2sev** [comment]
So if I run the old CVC4 binary (from pysmt) I get "unknown". If I run the latest CVC4 binary I get correct sat/unsat results.

**Comment by 2sev** [comment]
I replaced the old library _CVC4.so with a more-or-less new one (from [here](https://github.com/pysmt/CVC4)). Considering a simple script
```python
from pysmt.logics import LIA
from pysmt.typing import INT
from pysmt.shortcuts import Symbol, Or, ForAll, GE, Plus, Int, is_sat, Solver

a, b = [Symbol(s, INT) for s in 'ab']
f = ForAll([b], Or(GE(Plus(a, b), Int(0))))

with Solver(name='cvc4', logic=LIA) as s:
  print s.is_sat(f)
```
I got the following problem:
```
 Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/shortcuts.py", line 423, in is_sat
    return env.factory.is_sat(formula,
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/environment.py", line 143, in factory
    self._factory = pysmt.factory.Factory(self)
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/factory.py", line 76, in __init__
    self._get_available_solvers()
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/factory.py", line 235, in _get_available_solvers
    from pysmt.solvers.cvc4 import CVC4Solver
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/solvers/cvc4.py", line 25, in <module>
    import CVC4
  File "/home/aign/.local/lib/python2.7/dist-packages/CVC4.py", line 3092, in <module>
    STRING_SUBSTR_TOTAL = _CVC4.STRING_SUBSTR_TOTAL
AttributeError: 'module' object has no attribute 'STRING_SUBSTR_TOTAL'
```
which I then got rid of by commenting out the corresponding line in CVC4.py
```python
STRING_SUBSTR_TOTAL = _CVC4.STRING_SUBSTR_TOTAL
```
Since I know nothing about the code of pysmt, could you please tell me if that line was necessary? :)

**Comment by 2sev** [comment]
Actually, if I use CVC4 I get the following warning:
```
/home/aign/.local/lib/python2.7/site-packages/PySMT-0.4.3.dev1-py2.7.egg/pysmt/fnode.py:122: DeprecationWarning: MSSSubstituter will be deprecated in version 0.5
You should test your code with pysmt.substituter.MGSSubstituter.
  return _env().substituter.substitute(self, subs=subs)
```
Is it supposed to be there? Thank you.

**Comment by mikand** [comment]
Hi, 

sorry for the latency.

You did a great job in nailing down the problem! We will try to update the CVC4 version installed by installer.py as soon as possible.

I try to answer your questions.

* CVC4.py is a file that is auto-generated by the CVC4's SWIG. We only apply a minimal patch (https://github.com/pysmt/solvers_patches/blob/master/cvc4_wrapper.patch) to the CVC4 source tree to overcome a problem with the python bindings. Replacing the dynamic library should work if the CVC4 API is not changed too much: a better solution is to port the patch to the new version of CVC4 and then build the python bindings using the CVC4 building system.

* The warning is produced by PySMT regardless of the CVC4 version: we recently implementation a better version of the substitution (see #152) and we will soon switch to the new version also within solver wrappers. The warning is the current expected behavior, you can suppress warnings in the standard python way: https://docs.python.org/2/library/warnings.html#temporarily-suppressing-warnings

**Comment by 2sev** [comment]
Thank you! I will be waiting for a newer version of CVC4 in PySMT then.
