### ISSUE TITLE
Consider support for IPASIR

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#236]
This API has been introduced in SAT 2015. It is meant to be a common API for Incremental SAT Solving.

http://baldur.iti.kit.edu/sat-race-2015/index.php?cat=rules#api

**Comment by mikand** [comment]
Are you suggesting to implement a dedicated Python wrapper and a solver?

**Comment by marcogario** [comment]
Yes, both. I am not 100% about details, but in principle, with the same interface we should be able to wrap any of the solvers that took part into SAT Race 2015 Incremental track.

**Comment by prokls** [comment]
I just published my python interface corresponding to IPASIR. It might help you:
http://lukas-prokop.at/proj/snippets/py017.html

**Comment by marcogario** [comment]
Hi, thanks for letting us now. I think your work might be used to provide an IPASIR interface to the solvers that we already support. If you are interested, the next steps would be to compare our ```Solver``` class with the IPASIR interface that you developed. The goal is to understand whether each method of the IPASIR can be mapped into one (or more) calls to the ```Solver``` interface.

If this it the case, then we could create the actual component that does this mapping (e.g., as a mixin).  I have the feeling that this might not be the case, e.g., due to the ```failed``` method not being part of our ```Solver``` interface. However, it would be great if you could take a closer look, because if it is a matter of only one method, we can find a way around it.

Let me know if you are interested in working on this, and/or need any help!

Note: The other option is to use this interface to actually call an IPASIR solver.  If this sounds more interesting to you, I can elaborate further :)

**Comment by marcogario** [comment]
An example of using CFFI to access and IPASIR compliant solver is available in the repo  [1].
This needs to be packaged a bit better, but it is essentially what we need to provide access to IPASIR solvers from pySMT.

[1] https://github.com/marcogario/ipasir
