### ISSUE TITLE
issue in processing arguments for ExactlyOne()

### ISSUE THREAD

**Issue by hastyboomalert** [pysmt/pysmt#242]
Hi, 

I noticed that instantiating shortcuts.ExactlyOne() throws e.g.

TypeError: list() takes at most 1 argument (3 given)

at formula.py, line 480. I believe args shouldn't be unpacked in the list constructor. 

Martin

**Comment by marcogario** [comment]
Thanks for reporting this! Indeed it was a bug. A tentative fix is in PR #243.
