### ISSUE TITLE
Theory of Strings

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#245]
Introduce support for the Theory of Strings as described in http://cvc4.cs.nyu.edu/wiki/Strings .

Open Points:
- How far is this theory from being part of SMT-LIB ? Is there any outstanding issue that we should be aware of?
- What is the precise set of operators that need to be supported? All of the ones described in the wiki (Strings+Regexp)
- Is there any other solver supporting this theory (with a sub/super-set of the target operators)? 
- Where to find "SMT-LIB" examples for testing?

**Comment by marcogario** [comment]
See [CONTRIBUTING](https://github.com/pysmt/pysmt/pull/246/commits/ab5b759c059e5ef812bd059835d85b5b110f3d2b) for indications on how to proceed when introducing a new theory.

**Comment by sureshgl** [comment]
- Is there any other solver supporting this theory (with a sub/super-set of the target operators)?
    Googling on the same resulted a link related to Z3 supporting the Strings.[
    sequences]( http://rise4fun.com/Z3/tutorial/sequences)

**Comment by marcogario** [comment]
Consider the rewriting rules in Fig 2 of http://homepage.cs.uiowa.edu/~ajreynol/fmsd16.pdf for the Simplifier.

**Comment by marcogario** [comment]
#260 solves this for CVC4, without considering the theory of regexep.

**Comment by sureshgl** [comment]
Hi Macro,

Can I also do the changes for the  theory of regex. as that will be of use
for my protoptye.

Regards,
GL.


On Wed, Jun 8, 2016 at 1:06 AM, Marco Gario <notifications@github.com>
wrote:

> #260 <https://github.com/pysmt/pysmt/pull/260> solves this for CVC4,
> without considering the theory of regexep.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pysmt/pysmt/issues/245#issuecomment-224390058>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AB5h1EVRnhya9Wz2aYDcc67n2zua2oXRks5qJcgwgaJpZM4IL9m7>
> .
>



-- 
Suresh GL

**Comment by marcogario** [comment]
@sureshgl , yes. Please fork the branch ```strings```, and start working from there. I took care of updating it with the changes in master __including__ the Array's theory.

This is the list of operators and syntax that should be used (starting from CVC4 Wiki). Note that for the HR printing and parsing, I simplified the format into a function-like style ```str.len("s")```.

```
Type: RegExp

StrInRe:    Membership  (str.in.re X R) 	
StrToRe:    String to regular expression 	(str.to.re X R) 
ReConcat:   Regular expression concatenation 	(re.++ R1 ... Rn) 
ReUnion:    Regular expression union  (re.union R1 ... Rn) 
ReIntersect:Regular expression intersection  (re.inter R1 ... Rn)
ReStar (?): Regular expression Kleene star (re.* R)
RePlus (?): Regular expression plus 	(re.+ R) 
ReOption :  Regular expression option  (re.opt R)
```
For the type-checking, create and use the functions ```walk_regexp_to_regexp``` so that you can handle most operators in the same way. Then make a single function to type-check ```StrInRe``` and ```StrToRe```. 
Notice that the wiki doesn not discuss any Constant in the RegExp theory. 

For the rest, just follow what you did for strings (I guess you are an expert now ;) ).

**Comment by sureshgl** [comment]
Hi Marco,

Thank you for the opportunity and  clear cut directions.
Will get back to you with the code changes.

Regards,
GL.

On Wed, Jun 8, 2016 at 5:15 PM, Marco Gario <notifications@github.com>
wrote:

> @sureshgl <https://github.com/sureshgl> , yes. Please fork the branch
> strings, and start working from there. I took care of updating it with
> the changes in master *including* the Array's theory.
>
> This is the list of operators and syntax that should be used (starting
> from CVC4 Wiki). Note that for the HR printing and parsing, I simplified
> the format into a function-like style str.len("s").
>
> Type: RegExp
>
> StrInRe:    Membership  (str.in.re X R)
> StrToRe:    String to regular expression    (str.to.re X R)
> ReConcat:   Regular expression concatenation    (re.++ R1 ... Rn)
> ReUnion:    Regular expression union  (re.union R1 ... Rn)
> ReIntersect:Regular expression intersection  (re.inter R1 ... Rn)
> ReStar (?): Regular expression Kleene star (re.* R)
> RePlus (?): Regular expression plus     (re.+ R)
> ReOption :  Regular expression option  (re.opt R)
>
> For the type-checking, create and use the functions walk_regexp_to_regexp
> so that you can handle most operators in the same way. Then make a single
> function to type-check StrInRe and StrToRe.
> Notice that the wiki doesn not discuss any Constant in the RegExp theory.
>
> For the rest, just follow what you did for strings (I guess you are an
> expert now ;) ).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pysmt/pysmt/issues/245#issuecomment-224565539>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AB5h1GwyiKZOQQ_auoXbxgHKEN_yLkRBks5qJqtegaJpZM4IL9m7>
> .
>



-- 
Suresh GL

**Comment by marcogario** [comment]
Re Z3: https://github.com/Z3Prover/z3/blob/0870b4a5a0e3470b52b98aca4bca01df7b56ddef/src/ast/seq_decl_plugin.h

**Comment by marcogario** [comment]
Part of the release.
