### ISSUE TITLE
Python3.5: get_model does not work on SWIG 2.X wrappers

### ISSUE THREAD

**Issue by hsiswantoro** [pysmt/pysmt#255]
Hi,

I found that get_model is not working on Python3.5:

```
$ python3.5 puzzle.py 
[h, e, l, l, o]
Serialization of the formula:
((((1 <= h) & (h < 10)) & ((1 <= e) & (e < 10)) & ((1 <= l) & (l < 10)) & ((1 <= o) & (o < 10)) & ((1 <= w) & (w < 10)) & ((1 <= r) & (r < 10)) & ((1 <= d) & (d < 10))) & (((h + e + l + l + o) = (w + o + r + l + d)) & ((h + e + l + l + o) = 25)))
StopIteration

During handling of the above exception, another exception occurred:

SystemError: <built-in function delete_msat_model_iterator> returned a result with an error set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "puzzle.py", line 33, in <module>
    print(model)
  File "/usr/local/lib/python3.5/dist-packages/pysmt/solvers/solver.py", line 458, in __str__
    return "\n".join([ "%s := %s" % (var, value) for (var, value) in self])
  File "/usr/local/lib/python3.5/dist-packages/pysmt/solvers/solver.py", line 458, in <listcomp>
    return "\n".join([ "%s := %s" % (var, value) for (var, value) in self])
SystemError: <built-in function delete_msat_term> returned a result with an error set
```

Googling around suggest that it's a bug in Python 3.5.

**Comment by marcogario** [comment]
Hi, thanks for reporting this. We are currently testing only for 3.4, that is probably why it never came up. In the near future we should include also 3.5, but this might require some work to limit the scope of the CI (that is already quite big).

I'll have a look as soon as possible, if you have suggestions for possible fixes, please let us know.
Thanks!

**Comment by marcogario** [comment]
This seems to be a problem with the MathSAT wrapper. With Z3 this works.

**Comment by marcogario** [comment]
We have a new wrapper for MathSAT in the patch repository. The branch  i255/msat_py3  uses this wrapper and seems to work (this is a temporary fix, the next release of Mathsat should work with py3).

I am waiting on Travis to complete the tests, but if everything goes well, I'll open a PR for full support to python 3.5 in the next hours.

**Comment by marcogario** [comment]
See #287
