### ISSUE TITLE
Install.py is doing to much to check if a solver is installed

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#277]
When checking which solvers are installed, cmd/install.py is trying to instantiate a solver. This is unnecessary, since the Factory keeps a list of available solvers, accessible with the method ```all_solvers```. Using that method is the proper way to check if a solver is installed or not, we do it also in the tests' decorators ```skipIfSolverNotAvailable```.

My suggestion is to simplify this piece of code in order to obtain the list of installed solver from Factory. Same goes for Qelims.

[1] https://github.com/pysmt/pysmt/blob/master/pysmt/cmd/install.py#L70

**Comment by mikand** [comment]
Ok to skip instantiation of the solver. We should use the ```get_installed_version``` method of the installers to check if a solver is available.

**Comment by marcogario** [comment]
See #278 .
