### ISSUE TITLE
Floating Point Theory 

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#285]
Floating point is now the only theory from the SMT-LIB that we do not support.

Mathsat supports it, we can use its API to decide which operators to support.

**Comment by marcogario** [comment]
http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml

**Comment by shaobo-he** [comment]
Hello, @marcogario May I ask when floating-point theory will be supported? Anytime soon?

**Comment by shaobo-he** [comment]
I'd love to but my Python programming skill only allows me to write trivial programs. I'll let you know if I will do it.

**Comment by shaobo-he** [comment]
Hey @marcogario. Since I got more familiarized with pysmt through one of my recent projects, I'm willing to take the task of adding floating-point support. Please let me know if you or others are already working on it in order to avoid duplicating work.

**Comment by mikand** [comment]
I can confirm nobody is currently working on this, and any contribution is very welcome!
Let us know if you need any support or help

**Comment by shaobo-he** [comment]
Sounds good. I'll submit a PR once I get something working.

**Comment by miriameisenhofer** [comment]
Hello @shaobo-he , if floating-point support is still being worked on, do you have a rough time estimate for when it will be available?

**Comment by shaobo-he** [comment]
> Hello @shaobo-he , if floating-point support is still being worked on, do you have a rough time estimate for when it will be available?

Hello, I'm no longer working on floating point support. Please feel free to close this issue.
