### ISSUE TITLE
Lazy Native Nodes

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#289]
Native FNodes (as drafted in branch native_nodes) try to overwrite every node with a solver-specific node implementation. This requires a lot of work, since every operator needs to be considered. The advantage of this approach is that translation (forward and backward) is immediate, since we never need to navigate the formula. Nevertheless, with a smart use of caching (as currently done with the Converter), we can avoid this problem. Additionally, we still need to have a Python object for each Node, thus duplicating the memory.

An interesting place where to consider Native Nodes is in constants. Rational constants are currently handled via their string representation. This implies that, when number representation becomes nasty, crossing the API boundary is expensive (encoding+decoding of the string representation). The proposal is to be able to mix native FNodes with regular FNodes, and convert native FNodes lazily when needed.

For example, the back conversion on msat number could generate an MSatFNode, this node would be used as opaque object until we call `constant_value()` at that point, the conversion of the real constant takes place. Methods of the MSatFNode would then provide assurance that the returned object is still an MSatFNode (e.g., `MSatFNode.Times()` internally calls `msat_make_times` and wraps the result in a MSatFNode).

The difficulty in this proposal is to find a smart way to be able to enforce the use of Native nodes: in many situtations, regular FNodes are more than ok, and dealing with the complexity of native nodes would be an overkill. However, in those situations where native FNodes can make a difference, we would like to be sure that they are being used.

**Comment by mikand** [comment]
This is a nice idea, but currently a bit far fetched. Closing for now.
