### ISSUE TITLE
Fnode.constant_value should not return None if called on an expression

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#291]
Currently, calling ```constant_value``` on some expressions returns None (because the payload is None). 
This can lead to subtle bugs, and I think it never makes sense as a default.

There are two possible ways of going about it:

* When called on an expression, a ValueError exception is raised
* When called on an expression, simplification is performed if the expression is a constant expression, otherwise ValueError is raised

I think the 2nd solution is closer to what you'd expect from calling ```(Real(1) + Real(2)).constant_value()```

**Comment by ahmedirfan1983** [comment]
+1 for 2nd solution

**Comment by marcogario** [comment]
@mikand : Do  you see any issue with implementing solution 2? (When called on an expression, simplification is performed if the expression is a constant expression, otherwise ValueError is raised)

If not, please assign the issue to me and I'll implement it.

**Comment by mikand** [comment]
As always, I'm more for the "explicit is better than implicit" way. :smile: 

I think that your 1st solution is perfectly fine, while I see little benefit in implementing the 2nd because you can explicitly do as follows: 
```python
some_formula.simplify().constant_value()
```

Since simplification may be a time-consuming operation, I'm not sure it is a good idea to hide it.

My 2 cents

**Comment by marcogario** [comment]
#310 provides a more uniform solution to this problem.

The overall problem is due to the access to the payload of the node without confirming the type of the node (e.g., constant_value on a non constant). #310 adds assertions to test the type of the node when calling a method that makes assumption on the payload.
This implements solution 1 of the original comment. In my opinion this is better because it is less complex, and more local to the FNode structure, while providing enough feedback to the user so that it can choose how to proceed.
