### ISSUE TITLE
support for ntimes in Fnode

### ISSUE THREAD

**Issue by ahmedirfan1983** [pysmt/pysmt#297]
Current Fnode for times operator is a binary node, which makes rewriting an nary times expression difficult using the Identity dag walker. Such kind of rewriting would be a lot easier if pysmt has ntimes Fnode. 

for example:
sorting the following expression x*y*x (i mean the result should x*x*y) would be easier if we have ntimes Fnode.

**Comment by marcogario** [comment]
@mikand In order for this to be completed we need:

- [ ]  Support for n-ary Times (printing, oracles, solvers, etc.)
- [ ]  Flattening of n-ary Times in Simplifier

I would not bother now about sorting, and handle it in a separate issue. For your convenience, I created the branch  i297/nary_times  with the simplest examples and tests possible.

**Comment by mikand** [comment]
OK, I'll do this ASAP

**Comment by mikand** [comment]
See PR #304
