### ISSUE TITLE
Syncrhonize Versioning info

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#299]
We currently have the versioning info in 2 places, and it is not available from within pysmt.

The proposal is to create a VERSION file in the root of the project with the current version number. This file should be read by setup.py when creating a release, and by docs/conf.py when creating the documentation for the current version. 

Finally, I think that we need to provide a way within pySMT to access this information (even just ./install.py --version).

**Comment by mikand** [comment]
why not having a module pysmt.version that contains a single global variable? This would allow to query the pysmt version at runtime...

**Comment by marcogario** [comment]
Probably. The only doubt of having it in a variable in a module is that you need to import the module in setup.py or in the documentation generator. 

We need to try and see what happens.

**Comment by marcoroveri** [comment]
+1 for the var in the module

**Comment by mikand** [comment]
@marcogario This is similar to the approach taken by django (http://stackoverflow.com/a/4151796/1217394)

**Comment by marcogario** [comment]
There should be one obvious way of doing this... here are 6 :)
https://packaging.python.org/single_source_version/#single-sourcing-the-version

Ok for Django approach. See #303
