### ISSUE TITLE
Tests: Move serialization of examples within the examples

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#313]
The HR Serialization of the examples (from tests/examples.py) is stored in the file ```test_printing.py```. This means that everytime we add a new example, we need to modify two files. What often happens is that we forget to modify ```test_printing.py``` and tests fail during CI.

The proposal is to extend the ```Example``` class in order to include the HR String. This would work both as a documentation for the example itself (currently done with a comment containing something close to the HR representation), and would be used to test the HR printer.

This will force us to always provide the String representation.

**Comment by mikand** [comment]
Closed in #325
