### ISSUE TITLE
dReal Solver

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#330]
It would be nice to support the dReal Solver as a non-linear solver.

For an initial integration, it would be enough to support polynomials (avoiding all the transcendental operators supported by dReal). Integrating it means introduce support for delta-SAT as an optional answer of the solver. This changes a bit the interface to the solver, but I believe that delta-SAT will gain traction in more practical applications.

The current status of the integration (available in the branch `dreal`) is as follows:
- The repo pysmt/dreal3 (for of dreal3) has a preliminary python wrapper for dReal: https://github.com/pysmt/dreal3/tree/python_api/src/api 
- That wrapper is used in the branch `dreal` and all tests pass. This include the extension to delta-SAT. Delta-SAT is an exception that provides the precision as additional argument.
- The stub for the installer has been implemented but it does not seem to work properly.

The main activity here is to fix the installer for dReal with its python bindings.

**Comment by marcogario** [comment]
Most of the heavy lifting has already been done in the dreal branch. However, there is a lot of work to be done in order to get the installer to work, because dReal has a lot of dependencies and very long compilation times.

**Comment by marcogario** [comment]
The delta-SAT approach breaks many assumptions in pySMT. The integration of dreal is available in the tag but will not be actively maintained. If anybody is interested in maintaining this, please re-open the issue.
 
https://github.com/pysmt/pysmt/tree/archive/dreal_support

**Comment by pcarbonn** [comment]
I may have an interest in using dreal via pySMT (the alternative is to use it directly).  I'm curious what were the challenges you faced.  Could you give some examples ?  (I'm not familiar with the internals of pySMT (yet ?)).

**Comment by marcogario** [comment]
:wave: Thanks for taking a look at dReal/PySMT.

AFAIR there were 2 main issues mostly related to maintainability.
1- Building dReal was painfully slow and fragile. This made it very difficult to complete the installer 
(`pysmt-install dreal`), but also add it to our CI infrastructure.
2- When you start considering delta-SAT as the problem you are solving, you need to start accounting for the epsilon parameter in many places. While this is possible, and indeed the branch does so, it is hard to justify the additional complexity when none of the other solvers supports delta-SAT.

Given that this was >2yrs ago, it might be the case that both point are less valid than before. If that is the case, please let me know!

* I seem to remember that you would also loose double negation as a fundamental property. I.e., checking x is UNSAT does not mean that not(x) is Valid, since you need to account for the epsilon. As this was quite some time ago, I am unsure if this is really thecase. Nevertheless, we use this property in a few rewriting and other places, so removing the assumption needs to be done carefully.

**Comment by pcarbonn** [comment]
Thanks !  I appreciate it.

I can see the problem with "checking x is UNSAT does not mean that not(x) is Valid": this assumption is indeed used in the simplification algorithm.

There is a good chance we'll look at this in the next few months.  If we do, I may reopen the issue.

**Comment by aemartinez** [comment]
Hey, thanks for your work on pySMT. 

I'm trying to understand the implications of using pySMT with dreal. When you say you use the double negation property for rewriting, do you mean you assume (1) or (2) here:

1. `x is equivalent to not(not(x))`
2. `x is valid iff not(x) is unsat`

After reading the dReal paper (https://arxiv.org/abs/1204.3513), my understanding is that (1) should still hold for dReal, while it is (2) that needs to be taken with more care. 

Specifically, in Def. 3.2, it's clear that some formulas might be Unsat and delta-sat at the same time (for some delta). I see how this might undermine the conclusion one draws from dReal's output when aiming to prove the validity of a formula by checking its negation, but I don't see how this could impact the equivalence stated in (1) if this is used to preproces a formula before making any call to dReal.

If you could share any thoughts on this and the rewriting being made by pySMT, I would be grateful.

Thanks!

<img width="1016" alt="Image" src="https://github.com/user-attachments/assets/6f658bba-0cf0-494a-9087-527a6a229a50" />
