### ISSUE TITLE
Documentation: Proof Reading and Improvements

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#333]
Our documentation lives at https://pysmt.readthedocs.io/ .

Possible ideas to improve it:
- Try to go through the "Getting Started" section. Are all steps clear? Do you manage to run the example on your computer?
- The Tutorials section needs formatting. The examples live in examples/ and are included using `.. literalinclude:: ../examples/basic.py`. It would be nice to find a better way to better format them.
- Proofread, typos etc.

**Comment by chasingSublimity** [comment]
Rolling through the "Getting Started" section now!

**Comment by salman-bhai** [comment]
Is this Issue still open @marcogario ?

**Comment by marcogario** [comment]
The part related to proof reading and trying out the getting started section can always get additional eyes. 
In particular, if you are running on OSX or Windows this could be very beneficial (see issues #328 and #96) since we did not have many chances to experiment on those platforms.

Any feedback on the documentation is welcome. If you plan on doing some significant amount of work, please write here first so that we can coordinate.
