### ISSUE TITLE
Documentation: Extend docstrings of shortcuts.py with args type and return value

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#334]
The docstring for most functions in pysmt.shortcuts is minimal. It would be nice to include information about arguments and return value of these functions. As an example, look at ```is_sat```: https://pysmt.readthedocs.io/en/latest/api_ref.html#pysmt.shortcuts.is_sat 

There we use the Sphinx syntaxt to document the function:

```
    :param formula: The formula to check satisfiability
    :type  formula: FNode
    :param solver_name: Specify the name of the solver to be used.
    :param logic: Specify the logic that is going to be used.
    :returns: Whether the formula is SAT or UNSAT.
    :rtype: bool
```

The information for this should be rather simple to find: e.g., all is_* methods return a boolean, all formula constructors (And, Or..) take other formulae in input (i.e., FNode), etc.

**Comment by daj0ker** [comment]
Hi! Can I take this?

**Comment by marcogario** [comment]
Sure! Let us know if you run into problems or anything is unclear.

**Comment by marcogario** [comment]
@daj0ker, any progress on this? Feel free to commit partial results and ask for feedback.

**Comment by daj0ker** [comment]
@marcogario, Apologies, I've been busy. I'll get back to you with something concrete by the weekend.

**Comment by daj0ker** [comment]
Hi, how does [this](https://github.com/pysmt/pysmt/compare/master...daj0ker:extend-docstrings-shortcuts) look?

**Comment by marcogario** [comment]
That looks good! If you open a PR, I can give you more detailed comments (e.g., consistent empty line between description and parameters information).

In anycase, if you manage to do this for all the functions of shortcuts.py this would be very useful for us. Thanks!

**Comment by daj0ker** [comment]
Hi, I've managed to add docstrings to most functions. Check them out [here](https://github.com/pysmt/pysmt/commit/2aa3f279a7dd1863a7c1d2205e05b3608982884e).

A couple of issues:
1. I've modified some docstrings to begin with  `"""*` for review.
2.  I haven't documented math functions (the ones like `Div()`) as I wasn't sure how to document them.  

Thanks!

**Comment by marcogario** [comment]
Hi! Thank you very much for taking the time of doing this. Please open a PR against the branch  ```i334/docstrings```. In this way, I can easily change a few details before merging it into master.

When you open the PR, you'll be prompted by "clahub" to sign the CLA (Contributor License Agreement). This is a necessary step for me to accept your contribution. Thanks!

**Comment by daj0ker** [comment]
Done! See #362.
