### ISSUE TITLE
Documentation: Move Contributing guidelines to documentation

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#337]
The documentation has a section called "Developing in pySMT". This section should be extended with the contents of CONTRIBUTING. 

Ideally, the chapter would look like:
* Licensing (from CONTRIBUTING)
* Tests (Merge current content with the one in CONTRIBUTING) 
* How to add a new Theory (From CONTRIBUTING)
* Packaging
* Building documentation

The file CONTRIBUTING should only contain a link to the documentation, with a sentence along the lines:

"We welcome any type of contribution. Have a look at <link to documentation> for additional information, and please open an issue before starting any major activity, so that we can discuss the details."

**Comment by jthodge** [comment]
I've attempted to meet these Documentation requirements with #339. As this is my first FOSS contribution I welcome and look forward to any and all feedback.

**Comment by zeokav** [comment]
Is this still up?

**Comment by marcogario** [comment]
@zeokav: @jthodge is working on this. You can see that he already opened a PR and we are working to perfect it.

**Comment by marcogario** [comment]
Fixed in PR #339
