### ISSUE TITLE
Link to Google Group in Readme.md

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#342]
pySMT has a mailing-list/google group . This is not particularly visible, and in both the Readme and Documentation we share only the email address of the group, and not the webpage link.

The webpage link is https://groups.google.com/d/forum/pysmt
It would be nice to:

* Include this link with the name "Brows the Archives" in Readme.md (next to the email address pysmt@googlegroups.com)
* Find if there is any way to make this into a button/baddge "Mailing List" that links to the Google Group. This should look like (and be put next to) the ones for Travis, ReadTheDocs, PyPi, and License, that appear in next to the Title in the Readme.

**Comment by ankit01ojha** [comment]
I want to take it.

**Comment by anantprsd5** [comment]
I'm up for this

**Comment by nitishkd** [comment]
I have made a patch. Please review it.
