### ISSUE TITLE
Deprecate Solver.declare_variable

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#356]
```Solver.declare_variable``` is not used in the code, except for internal reasons of the solvers (Picosat and Bdd), see [1] I think this should not be part of the Solver interface.

My recommendation is to deprecate it (without replacement) and eventually remove this function.

[1] https://github.com/pysmt/pysmt/search?utf8=%E2%9C%93&q=declare_variable

**Comment by mikand** [comment]
:+1:

**Comment by marcogario** [comment]
PR #369
