### ISSUE TITLE
Proposal: remove redundant entries from BddSolver's assertion stack

### ISSUE THREAD

**Issue by colinmorris** [pysmt/pysmt#367]
Since the more aggressive formula simplifier uses BddSolver under the hood, I had hoped that solver might have better memory characteristics when iteratively adding many assertions. It seems like the opposite is true though - it uses around 10x as much memory as msat, when adding the same assertion over and over in a loop.

Right now the solver maintains a list, `assertion_stack`, which stores, for each assertion added, the original pySMT formula, and the BDD representation.

However, immediately after a call to `solve`, the only entries in the stack that are "live" (i.e. are used by any of the solver's public methods) are the last entry, plus any entries referred to in `self.backtrack`, which is appended to every time `push()` is called.

Seems like culling all those dead entries would have a huge impact on memory, at basically no cost (except a little extra bookkeeping).

If this sounds reasonable, I'd be happy to try to write a pull request for this.

**Comment by colinmorris** [comment]
Actually, I just tried making this change, and it helps for a toy example (adding the same assertion millions of times in a loop), but in the real code that sent me down this path, it has virtually no effect. Something is using a lot of memory (relative to the other solvers), but it's not `assertion_stack`. I'll keep poking around.

**Comment by mikand** [comment]
@colinmorris If you have very big formulae, using the BddSimplifier is not a good idea. BDDs have this bad habit of exploding in memory... :smiley:

Moreover, using BDDs for simplification pays off only if the Boolean part of the formula is very complex with respect to the theory part, otherwise you are only wasting time and memory...

If you can share some hints about the kind of problem you are trying to solve we might be of help:
- Which kind of theory (if any) are you using?
- Which features do you need? (incrementality, unsat-cores, ...)

**Comment by colinmorris** [comment]
My code is [here](https://github.com/colinmorris/openai-gym-sandbox/blob/master/algorithmic/constraint/algo_constraint.py). 

If you run `algo_constraint.py 'RepeatCopy-v0' 'msat'`, it finds a solution after a minute or two, and maxes out under 50 MB of memory.

Running `algo_constraint.py 'RepeatCopy-v0' 'bdd'`, I find the process has used 5 GB of memory after 2 minutes (and still hasn't reached 500 iterations, which z3 or msat are able to do in under 10 seconds). If I let it run longer, it will eat up my 12 GB of ram well before finding a solution.

(If you want to actually run the code, you'll need to pip install gym.)

I'm just using QF_BOOL. I think incrementality is the only feature I need. (Though I'm not 100% clear on what that means in this context. I am making many interleaved calls to `add_assertion` and `solve`. I'm not doing any kind of push/pop transactions though.)

My use case is kind of weird. I'm trying to solve some simple reinforcement learning problems (like reversing the characters on an input tape), using boolean variables to encode rules for interacting with the environment. I have on the order of 100 variables, and I'm repeating this a whole bunch of times in a loop:

- ask the solver for a model
- add a new assertion

The formula being asserted will always be the Or of a bunch of literals. I think the literature sometimes refers to such things as *nogoods*? They may sometimes be pretty long. They will never be repeated.

(The new rule is arrived at by following the policy encoded by the model returned by the solver, until we encounter a failure. The nogood is the Nand of the rules that led to that failure.)

The reason  I started looking into BDD and simplification is that I'm adding a lot of rules (10's or 100's of thousands) over a relatively small number of variables, so it seems like the simplification of those rules could end up being a lot smaller than the sum of their parts. Maybe I'm not understanding the purpose of simplification though.

But even if BDD isn't the right tool for this problem, the massive discrepancy in memory usage between it and other solvers on this problem seems a little alarming, and makes me wonder if there's some kind of leak going on. After investigating it a bit, I can at least say it's not a problem with `assertion_stack`. Most of the memory growth seems to be happening in the call to `self.converter.convert` in `BddSolver.solve`. It doesn't seem to be a problem with the memoization cache - setting `invalidate_memoization` to True in DagWalker didn't help. I suspect something is going on outside of python-land, and my ability to understand/debug the `repycudd` stuff has been pretty poor.

**Comment by marcogario** [comment]
As a general comment (I didn't manage to go through your code yet) the behavior that you are getting is to be expected. 

The BDD solver uses (RO)BDDs [1] to represent the formula. A bdd represents **all** solutions/models to the formula, while an SMT/SAT solver usually provides you with one solution. For this reason, the two cannot be directly compared.
BDDs are also very sensitive to the order in which you define the variables (there are a few options in pySMT to control that explicitly), and there are orderings for which the same problem can have an exponentially more compact representation.

My main advice would be to rely on an SMT solver like msat or z3, or on a SAT solver like picosat, and do not worry too much about simplification, unless you start seeing a very big slow down. Most solvers are able to handle this type of flow quite efficiently.

In general, your idea of using BDDs to keep a compact version of the bad region (the nogoods), is correct but requires using both a BDD and an SMT solver. You will use the BDD to represent the bad region, and periodically (every X hundred iterations) destroy and recreate the SMT solver with the problem description + current bad region (note that in the BDD you only store the bad region, not the original problem). Again, this is a type of optimization that might make your code much more complex, without a real advantage. 

[1] https://en.wikipedia.org/wiki/Binary_decision_diagram

**Comment by marcogario** [comment]
I took a quick look at the code, and it looks good. If you run into performance issues, one thing you might consider is getting rid of the ExactlyOne constraint. That is (in the current implementation) a quadratic constraint. Depending on how many variables you have in the domain, it might be a big constraint. We usually avoid using that by using a theory, such as Integers or Bitvectors.

**Comment by colinmorris** [comment]
Thanks Marco. Not sure if it's in scope for this project, but I think it'd be really helpful to have a section in the docs on choosing a solver. I tried following the external links in the README, but didn't really get a sense of the pros and cons of each solver, or what kinds of problems they were well-suited for. I'm still not clear on when you would want to use BddSolver, for example.

(Also, the ExactlyOne constraints in the code are only acting on groups of at most 5 or 6 variables, so I'd be surprised if their scaling was a problem. But I'll try Integers/Bitvectors.)

**Comment by marcogario** [comment]
Thanks for the feedback. Not sure when we will get around in doing this, but I open an issue #373 .

The BddSolver is the only one to be significantly different. For the rest, if you only need SAT (without theories), you should give picosat a try. 
If in this (or future) projects you need theories, you should use the solvers depending on which theory they support, and then experiment with your specific domain. It is hard to have a generic "this is better" answer. For an overview of performances, you can take a look at the SMTComp [1]

[1] http://smtcomp.sourceforge.net/2016/results-summary.shtml?v=1467876482
