### ISSUE TITLE
SMT-LIB: Interpreting Symbols in annotations leads to unexpected results

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#370]
The branch ```annotations_parsing``` shows that annotations are interpreted. If an annotation contains the name of a symbol, it is treated as a symbol, otherwise as a string. The test in the branch shows this behavior. 

The main issue is that the symbol is being escaped when treated as an annotation, therefore the name of the symbol contains spurious ```\```. The expected behavior is that ```get_symbol``` at the end  of the test succeeds.

**Comment by mikand** [comment]
Fixed in #374
