### ISSUE TITLE
CVC4 in PySMT.

### ISSUE THREAD

**Issue by 2sev** [pysmt/pysmt#380]
Hi guys,

First, thank you for your amazing work on PySMT! It's extremely convenient to use. 

And second, I would like to know how to install CVC4 from PySMT these days. Using `pysmt-install --cvc4` does not report any issue. In the end, I get the following lines printed:

```
===============================================================================
This CVC4 build was configured with:
  configure --prefix=/home/aign/.smt_solvers/python-bindings-2.7/CVC4_bin --enable-language-bindings=python --with-antlr-dir=/home/aign/.smt_solvers/cvc4/CVC4-c15ff43597b41ea457befecb1b0e2402e28cb523/antlr-3.4 ANTLR=/home/aign/.smt_solvers/cvc4/CVC4-c15ff43597b41ea457befecb1b0e2402e28cb523/antlr-3.4/bin/antlr3
===============================================================================

make[2]: Leaving directory `/home/aign/.smt_solvers/cvc4/CVC4-c15ff43597b41ea457befecb1b0e2402e28cb523/builds/x86_64-unknown-linux-gnu/production'
make[1]: Leaving directory `/home/aign/.smt_solvers/cvc4/CVC4-c15ff43597b41ea457befecb1b0e2402e28cb523/builds'
```

However, running `pysmt-install --check` after installing CVC4 gives the following output:

```
aign@centaurus:~$ pysmt-install --check
Installed Solvers:
  msat      True (5.3.8)             
  z3        True (4.4.2)             
  cvc4      False (None)              
  yices     True (2.5.1)             
  btor      True (2.2.0)             
  picosat   True (960)               
  bdd       True (2.0.3)             

Solvers: bdd, msat, yices, cvc4, picosat, btor, z3
Quantifier Eliminators: bdd, msat_lw, shannon, msat_fm, z3
UNSAT-Cores: z3, msat
Interpolators: msat, z3
```

Is there a specific issue with CVC4? Should I install it in some other way?

Thanks,
Alexey

**Comment by marcogario** [comment]
You are doing correctly. This is a bug, and i will look into it.

By anychance, do you have both python 2 and 3 installed? I had a similar
issue some time ago on my laptop but then i didn't manage to reproduce it.

**Comment by 2sev** [comment]
Yes, I have both python2 and python3 installed on my machine. But notice that I was able to install all the other solvers on the same machine using `pysmt-install`.

**Comment by marcogario** [comment]
Yes, the issue (AFAIU) is due to the way that CVC4 building system calls the python interpreter. In fact I recently added a check for this [1] but it probably it does not always work. 

https://github.com/pysmt/pysmt/blob/master/pysmt/cmd/installers/cvc4.py#L57

**Comment by marcogario** [comment]
Which version of pySMT are you using? Could you try a checkout from master?

If you go in the directory: ```/home/aign/.smt_solvers/python-bindings-2.7/``` you should find a file ```CVC4.py``` and ```_CVC4.so```. In that directory, can you execute: ```python -c "import CVC4"```. That command should suceed.

**Comment by 2sev** [comment]
I am using the version from master.

Yes, if I go to `$HOME/.smt_solvers/python-bindings-2.7/`, there are files `CVC4.py` and `_CVC4.so`, as well as directory `CVC4_bin`. If I do either `import CVC4` or `import _CVC4`, it does not complain. Even if I do it from any other directory (`$HOME/.smt_solvers/python-bindings-2.7/` is in my `PYTHONPATH`). However, pysmt does not detect its own installation of CVC4. :)

**Comment by marcogario** [comment]
Pysmt finds the bindings, but they are not working correctly. 

If you look at the result of check, you can see that cvc4 appears in the list of Solvers (i didn't notice that the first time). What it fails to do is getting the version number. The code to do that is in installers/cvc4.py :
```
import CVC4
                version = CVC4.Configuration_getVersionString()
```

Maybe you can try that?

**Comment by 2sev** [comment]
Sure, this is what I get:
```
import CVC4
print CVC4.Configuration_getVersionString()
1.5-prerelease
```

**Comment by marcogario** [comment]
ok, I was expecting that command to fail, since that is exactly what we do in the installer :confused: .

Could you please go ahead and just use CVC4 to solve a toy example with pysmt? We need to understand whether it is a problem of ```--check``` or the bindings are actually not working in some way.

Does an example such as the following work?
```python
print(get_model(FreshSymbol(), solver_name='cvc4'))
```

also note that pysmt-install uses ```/usr/bin/env python``` to run the command, so please make sure that  you are using python 2 consistently everywhere.

**Comment by 2sev** [comment]
So, this command succeeds when I run it from the Python command-line, but it fails if ran from the `installers/cvc4.py` file. This is weird because the interpreter seems to be the same. It's `python2.7` in both cases.

**Comment by 2sev** [comment]
Just to check, I added the following line into `installers/cvc4.py`:

```python
import CVC4
print dir(CVC4)  # the line added
print CVC4.Configuration_getVersionString()
```
Now, if I run `pysmt-install --check`, I get the following output:
```
aign@centaurus:~$ pysmt-install --check
Installed Solvers:
['CVC4Installer', 'SolverInstaller', 'TemporaryPath', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'os', 'sys']
  msat      True (5.3.13)            
  z3        True (4.4.2)             
  cvc4      False (None)              
  yices     True (2.5.1)             
  btor      True (2.2.0)             
  picosat   True (960)               
  bdd       True (2.0.3)             

Solvers: bdd, msat, yices, cvc4, picosat, btor, z3
Quantifier Eliminators: bdd, msat_lw, shannon, msat_fm, z3
UNSAT-Cores: z3, msat
Interpolators: msat, z3
```

I presume that `import CVC4` actually imports some other module named the same if ran from `pysmt-install`. Does it import itself? If yes, why? :)

**Comment by 2sev** [comment]
OK, if I print the file of the CVC4 module imported, it says `/home/aign/.local/lib/python2.7/site-packages/PySMT-0.6.1dev1-py2.7.egg/pysmt/cmd/installers/CVC4.pyc`.

**Comment by marcogario** [comment]
The issue seems to a be a relative import, are you on OSX? This might have to do with case-sensitivity of the filesystem...

**Comment by 2sev** [comment]
No, this is an Ubuntu machine.

**Comment by marcogario** [comment]
Yes, that should point to the file in python-bindings. The problem is that ```CVC4.pyc``` should not exist in upper-case within installers. Is there also a .py? If not, you can just delete the .pyc.

**Comment by 2sev** [comment]
The funny thing is that there is no such file. The file I have in the installers is lower-case `cvc4.pyc`.

**Comment by marcogario** [comment]
I can reproduce the issue by doing the opposite (renaming the import into ```import cvc4```). Add the following at the top of installers/cvc4.py :

```python
from __future__ import absolute_import
```
it should work. Also, if you have python 3, I think it should not be affected by this.

**Comment by 2sev** [comment]
OK, thank you! Finally, it determines the CVC4 solver. However, if I call `get_model()`, it prints 

```python
  File "/home/aign/test.py", line 64, in solve
    fmodel = get_model(self.formula, solver_name='cvc4')
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.6.1dev1-py2.7.egg/pysmt/shortcuts.py", line 814, in get_model
    logic=logic)
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.6.1dev1-py2.7.egg/pysmt/factory.py", line 486, in get_model
    incremental=False) as solver:
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.6.1dev1-py2.7.egg/pysmt/factory.py", line 457, in Solver
    **options)
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.6.1dev1-py2.7.egg/pysmt/factory.py", line 104, in get_solver
    **options)
  File "/home/aign/.local/lib/python2.7/site-packages/PySMT-0.6.1dev1-py2.7.egg/pysmt/solvers/cvc4.py", line 83, in __init__
    self.em = CVC4.ExprManager()
AttributeError: 'module' object has no attribute 'ExprManager'
```

**Comment by marcogario** [comment]
Same issue there. Modify solvers/cvc4.py to use absolute_import .

This really seems a problem of case-sensitivity of the filesystem. Which version of Ubuntu and filesystem are you using?

**Comment by marcogario** [comment]
See PR #382 .

**Comment by 2sev** [comment]
Thanks! Indeed, absolute_import solves the issue.
