### ISSUE TITLE
FNode.get_dependencies() should become a walker

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#39]
FNode.get_dependencies() is implemented recursively within FNode (via compute_dependencies).
This means that:

- The formula TREE is visited
- On deep formulas we have problems of recursion
- It is not extensible when new node types are introduced.

We can either replace compute_dependencies with a call to a proper walker, or we can introduce an additional method (to keep get_dependencies simple and independent from the environment).

**Comment by mikand** [comment]
Actually, the formula is NOT visited as a tree: dependencies are cached, thus they are never re-computed.

I think the first proposed solution is more pysmt-style. Do you see any performance advantage in the second solution?

**Comment by marcogario** [comment]
Done in PR #44
