### ISSUE TITLE
serialization of formulas should use `daggify=True` by default

### ISSUE THREAD

**Issue by agriggio** [pysmt/pysmt#397]
rationale: if you want exponential blow-up, you should ask for it

**Comment by mikand** [comment]
Are you referring to the serialization of SmtCommands? (https://github.com/pysmt/pysmt/blob/175b9e0d504a8c546fea75a4563752da0b196b36/pysmt/smtlib/script.py#L45)

**Comment by agriggio** [comment]
yes, sorry if it was unclear. we noticed it when dumping scripts

**Comment by marcogario** [comment]
See PR # 399.
