### ISSUE TITLE
Potential get_values and get_py_values issues

### ISSUE THREAD

**Issue by pafede2** [pysmt/pysmt#408]
Dear PySmt developers,

beforehand, thanks a lot for developing this great tool.

I bother you regarding the following potential issue on PySmt. I've just
being playing around with PySMT. Even if this issue came up on a more
general context, the minimal example is the following. I am trying to
obtain the model out of the this formula:

((a = 1) & (b = 2))

The steps I've performed are the following:

1.Check for satisfiability
2.Get the model

However, when performing the second step I get this message:

`
ERROR: test_func_get_values (test_pysmt.TestArray)
Traceback (most recent call last):
  File "test_pysmt.py", line 43, in test_func_get_values
    model_values = model.get_values(self.formule)
  File
"path_to_virtualenvs/env_1/local/lib/python2.7/site-packages/pysmt/solvers/solver.py",
line 457, in get_values
    for f in formulae:
  File "path_to_virtualenvs/env_1/local/lib/python2.7/site-packages/pysmt/fnode.py",
line 829, in __getitem__ raise NotImplementedError
NotImplementedError
`

Everything works fine if I change the this line
<https://github.com/pysmt/pysmt/blob/master/pysmt/solvers/solver.py#L166>
from:

`for f in formulae`

to:

`for f in formulae.get_atoms()`

I was wondering whether this is an actual issue or I am misunderstanding something. In addition, I am not confident that this fix may solve completely the issue but the minimal example.

I attach the test cases I've created.

Best,
Federico Dobal.-

**Comment by mikand** [comment]
Dear Federico,
thanks for using pysmt.

I think there is a misunderstanding on how `get_values` works.
Consider this example:
```python
from pysmt.shortcuts import *

a = Symbol('a', INT)
b = Symbol('b', INT)
f = And(Equals(a, Int(1)), Equals(b, Int(2)))
with Solver(logic="QF_LIA") as s:
    s.add_assertion(f)
    check = s.solve()
    assert check is True
    print("a = %s" % s.get_value(a))        # prints "1"
    print("b = %s" % s.get_value(b))        # prints "2"
    print(s.get_values([a, b]))                   # prints "{a: 1, b: 2}"
    print(s.get_value(f))                            # prints "True"
    print(s.get_value(Equals(a, Int(2))))   # prints "False"
    print(s.get_model()) # prints "a := 1\nb := 2"
```

As you can see, you ca ask the `get_value` of any formula to the solver, that evaluates the formula on the model generated during the satisfiability check.

`get_values` is only a shorthand to quickly get many values without cycling over a list (or any iterable) of formulae.

As a final note, consider the method `get_model` that gives you a "dictionary-like" object with all the variables assigned in the model found by the solver. The object returned by `get_model` also has a `get_value` method that allows you to query the value of arbitrary terms (see https://github.com/pysmt/pysmt/blob/master/pysmt/test/test_models.py).

Hope this helps,

Andrea

**Comment by pafede2** [comment]
Indeed, you are right!

It was a misunderstanding!

Sorry for the noise and thanks a lot for the guidance!

**Comment by mikand** [comment]
@pafede2 You are welcome. 

If you want, you can also use the dedicated mailing list (pysmt@googlegroups.com) for any question or discussion regarding pysmt.

Cheers,

Andrea
