### ISSUE TITLE
SMT-LIB Serialize performance issue

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#416]
```
import time
from six import StringIO

from pysmt.shortcuts import read_smtlib, reset_env
from pysmt.smtlib.parser import SmtLibParser

start = time.time()

reset_env()
buf = StringIO()
parser = SmtLibParser()
script = parser.get_script_fname("pysmt/test/smtlib/fuzzed/AUFNIRA.smt2.bz2")
assert script is not None
tparse = time.time()
script.serialize(buf)
tdump = time.time()

print(tparse-start, tdump-tparse)
```

The example above outputs:

```
(0.0475311279296875, 9.41358995437622)
```

Meaning that it takes ~0.05s to read the smtlib script but ~10s to serialize it!

There are 3 files form the fuzzed testcases that have this type of behavior, leading to a runtime for test_fuzzed.py of 41s. The test has been marked as slow, but we should look into better understanding this performance bottleneck.

**Comment by mikand** [comment]
The problem here is that `script.serialize(buf)` does not produce a daggified output by default. In fact just by running the same script with `script.serialize(buf, daggify=True)` I get:
(0.05760908126831055, 0.0440669059753418)

**Comment by marcogario** [comment]
See #418 . I think our intention for #397 was also to cover this case, but we missed it.
