### ISSUE TITLE
CVC4: Potential memleak in python wrapper/solver

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#417]
Running the whole test suite with CVC4 requires close to 3GB of RAM:
```$ PYSMT_SOLVER="cvc4" runlim nosetests pysmt/test/```

This seems to suggest that resources are not being freed when we destroy a CVC4 Solver object. This might either be an issue in the python bindings, in CVC4, or in our pySMT keeping alive the solver and preventing garbage collection (unlikely). 

For a comparison, msat runs with 1.5GB and z3 with 500MB.

**Comment by marcogario** [comment]
The SWIG wrapper does not free the solver (and probably the expression manager).
By patching CVC4.py 8949 with the following:
```
    #__del__ = lambda self: None
    def __del__(self):
        print("****DEL")
        _CVC4.delete_SmtEngine(self)
```

The solver is free'd and the test-suite requires only 900MB to run. This requires patching the SWIG wrapper of CVC4.

**Comment by mikand** [comment]
Can we add the `_CVC4.delete_SmtEngine(self)` in the destructor of our CVC4Solver as a temporary workaround?

**Comment by marcogario** [comment]
See #419 for a temporary workaround. Leaving the issue open until we get a proper patch for CVC4.

**Comment by 4tXJ7f** [comment]
Just came across this issue by coincidence. I created an issue in the CVC4 repo: https://github.com/CVC4/CVC4/issues/1523. Feel free to post other CVC4-related issues over there :)

**Comment by 4tXJ7f** [comment]
I have created a branch (https://github.com/4tXJ7f/CVC4/tree/fix1523) that hopefully finally addresses the issue (PR is here: https://github.com/CVC4/CVC4/pull/3753). I'd very much appreciate if you could test the fix and see if it works as required.

Thank you!

**Comment by marcogario** [comment]
See https://github.com/cvc5/cvc5/pull/4422#pullrequestreview-433765786 . 
The issue is not planned to be fixed upstream. Our local patch will do for the time being.

Upgrading to cvc5 and their new python bindings is the suggested path forward. Nothing to do here.
