### ISSUE TITLE
MAXSMT capabilities?

### ISSUE THREAD

**Issue by varunpatro** [pysmt/pysmt#475]
Hello,

Z3 supports specifying soft constraints and hard constraints to solve a MAXSMT problem. This is done via the `assert-soft` command.

Source: https://rise4fun.com/Z3/tutorialcontent/optimization

I want to find out how I can rely on this Z3 capability to express some optional and "soft" constraints.

**Comment by mikand** [comment]
@varunpatro Hi, unfortunately pysmt does not currently support MAXSMT at all. We do have an experimental branch called `optimization` with some basic optimization features (optimization of a cost function and a pareto-optimization of cost functions). Clearly you could use those to encode a MAXSMT problem, but I doubt this would be competitive with a native MAXSMT solver.

I suggest you directly use the z3 python interface:
```python
from z3 import *

a = Real('a')
b = Real('b')

opt = Optimize()
opt.add(a + b == 3) # hard constraint
opt.add_soft(a > 0) # soft constraint

print(opt.check())
print(opt.model())
``` 

We hope to fully support optimization in pysmt in the future.

**Comment by varunpatro** [comment]
Hi @mikand,

Thanks for sharing the example. Using z3 looks really promising. The z3 library also looks quite similar to pysmt so I can port my code with minimal changes.

Thanks for sharing the example, and hoping to see full optimization support in the future :)
