### ISSUE TITLE
Typechecking mixed Integer and Real expression

### ISSUE THREAD

**Issue by france194** [pysmt/pysmt#480]
Hi guys, I am a student and I am working with pysmt, more specifically I am using the parser to read smtlib2 input files. The problem is that I am obtaining PysmtTypeError when in the file appears expressions like this:

(157/2 * ((2 * used_machines) + 8))

and used_machines is so defined:

(declare-fun used_machines () Int)

Reading your code I saw that when there is an expression with Integer and Real constants, the Integer constants are converted to Real but for the 'variables' this is not happening, right? Is there any way to solve the problem, so to convert temporary used_machines into Real?

Thanks

**Comment by mikand** [comment]
@france194 Thanks for using pysmt.

As a design choice, we built pysmt with a very strict policy for implicit integer conversion. In fact, your example is wrong as you are multiplying a rational number with an integer expression. The SMT-Lib solution to this is to use the `(to_real)` explicit cast:

```
(declare-fun used_machines () Int)
(assert (>= (* (/ 157.0 2.0) (to_real (+ (* 2 used_machines) 8))) 0))
(check-sat)
```
Should work fine

Within python, you will also need to use the `ToReal()` shortcut when you combine your integer expressions with real-typed ones.

Hope this helps,

Andrea

**Comment by france194** [comment]
Thank you for your answer and help!
Francesco
