### ISSUE TITLE
Warnings when using shortcuts

### ISSUE THREAD

**Issue by mikand** [pysmt/pysmt#490]
On my installation of python 3.6, just by importing the `pysmt.shortcuts` module, I get the following warnings:
```
/usr/lib/python3.6/importlib/_bootstrap_external.py:426: ImportWarning: Not importing directory /home/amicheli/.local/lib/python3.6/site-packages/zope: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
/usr/lib/python3.6/importlib/_bootstrap_external.py:426: ImportWarning: Not importing directory /usr/lib/python3/dist-packages/keyrings: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
/usr/lib/python3/dist-packages/pyximport/pyximport.py:53: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
```

This is quite annoying, but because the shortcuts module imposes the default warnings filter it is impossible for a client application to disable these warnings.

In fact, in shortcuts.py we have the following code that forces the default warning:
```python
# Enable default deprecation warnings!
import warnings
warnings.simplefilter('default')
```
This prevents a client application do suppress those warnings.

My suggestion is to remove the code above from shortcuts.py and leave to the use the selection of the warning level.

**Comment by mikand** [comment]
@marcogario What do you think?

**Comment by marcogario** [comment]
This is because your code looks like:
```
from pysmt.shortcuts import is_sat
from modulex import y
```` 
?

I do not think that disabling the warnings is a good idea, but I agree that they might need to be made more focused. The purpose of that line of code is to ensure that users will be alerted of deprecations and other issues within pySMT. Can we change the filter to achieve this?

**Comment by mikand** [comment]
No, my code is like
```
from m import x, y, z
from pysmt.shortcuts import is_sat
```
but there are modules (i.e. importlib) installed in ubuntu by APT that have warnings, and the shortcuts indirectly import them (should be something like shortcuts -> parser -> cython -> imp -> importlib).

Anyway, in my opinion it is bad for a library to force the user to a specific warning level (even if you invoke the code with `python3 -W ignore` you still see the warnings as the module forces them to be enabled!). Shouldn't this a choice to be done by the client applications?

**Comment by marcogario** [comment]
I agree on fixing this so that we do not show warnings outside of pysmt. However, we should enforce that the ones inside pysmt are shown. 

Notice that the idea of doing this in shortcuts is that this is a bit of a special module that is used for exploration. I agree that if you import the rest of the library, you should not see anything you did not ask for.

**Comment by marcogario** [comment]
There are options for the filter. See filterwarnings from
https://docs.python.org/3.6/library/warnings.html

We could use the module keyword to limit the warnings to those inside pysmt. What do you think?

**Comment by mikand** [comment]
AFAIK the module filter only limits to once per module the number of times the same kind of warning is printed... So it is not what we would need here... Am I missing something?

**Comment by marcogario** [comment]
Not the value module in the keyword action, but the keyword module. I cannot try now, but if you want I can test it next week.

**Comment by mikand** [comment]
Indeed the module keyword works perfectly, I tried to generate a warning within pysmt and it is shown, while the other external warnings are hidden!
