### ISSUE TITLE
SmtLibScript.evaluate() raises NotImplementedError for (declare-sort)

### ISSUE THREAD

**Issue by yoni206** [pysmt/pysmt#499]
Although support for (declare-sort) seems to have been added [here](https://github.com/pysmt/pysmt/pull/411), it raises a `NotImplementedError` when evaluated through `SmtLibScript`.
To reproduce:
Run `python tmp.py`, with `tmp.py` having the following content:
```
from pysmt.smtlib.parser import SmtLibParser
from pysmt.smtlib.script import SmtLibScript
from pysmt.shortcuts import Solver
import os

def main():
    smtlib_script = '(declare-sort s 0)'
    tmp_file_name = "tmp.smt2"
    tmp_file = open(tmp_file_name, 'w')
    tmp_file.write(smtlib_script)
    tmp_file.close()
    parser = SmtLibParser()
    script = parser.get_script_fname(tmp_file_name)
    script.evaluate(Solver('z3'))
    os.remove(tmp_file_name)

if __name__ == "__main__":
    main()
```

**Comment by yoni206** [comment]
I think that a solution would be adding a case `elif cmd.name == smtcmd.DECLARE_SORT` around [here](https://github.com/pysmt/pysmt/blob/b0324e68bee72c862db9620206a34f2e20c38160/pysmt/smtlib/script.py#L320), like I did [here](https://github.com/yoni206/pysmt/tree/declare-sort-bug). Should I submit a PR?

**Comment by marcogario** [comment]
Thanks for taking the time of looking into this. It seems like you are testing our SMT-LIB support quite a bit :)

Most likely I forgot to extend this. The change you suggest looks reasonable, if you can add a test and open a PR that would be great!

**Comment by marcogario** [comment]
These are typically nasty bugs to debug, and we recently had a similar one with Z3 (#465). Sometimes builds on Travis fail due to non-deterministic conditions. I would invite you to create the PR and see whether this can be reproduced; otherwise we can simply ignore the failure until we find a better way to debug it.

**Comment by yoni206** [comment]
Done #501. See you there :)
