### ISSUE TITLE
Python 2: Deprecation

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#504]
Python 2.7 will not be maintained in 2020 (18 months from now). Python 3.7 was released a few days ago, and overall Python has significantly evolved as a language, with many aspects that we should consider embracing (e.g., static typing of the core functionalities).

How can we deprecate Python 2 in pySMT? The main con I see is that pypy is still mostly python 2 (although pypy3 has made some good progress). The advantages I see are:
- Avoiding the dependency from six (to which we owe a debt of gratitude)
- Reduce the matrix of testing in our CI
- Improve performance and quality of code

My proposal for deprecation is that the next release (0.8.0 ?) will be the last one to officially support python 2.7, with the end-of-life support for the successive release (0.9.0?)  This means:
- Bug fixes after 0.8.0 (but before 0.9.0) will be backported to a dedicated branch python27 
- No new features will be added in the python27 branch after the release of 0.8.0
- CI for 2.7 will be disabled from master after 0.8.0 and only enabled on the python27 branch

Since we are very flexible with our releases, I think we should plan to have 0.8.0 before the end of this year (October?) and 0.9.0 no later than 6 months from then. The short 6 months window for support on 0.8.0 is due to our limited resources. If somebody wants to continue backporting bugfixes after 0.9.0 I will be ok with it.  

@mikand @cristian-mattarei do you know of anybody still using python 2?

**Comment by mikand** [comment]
Personally I used Python 3 since quite some time I have no problems in dropping the support for Python 2. I just sent an email to our unit to see if somebody is still using Python 2 on active projects.

**Comment by marcogario** [comment]
I tried to upgrade the CI to pypy3.5 . It seems that the binary distribution has quite some issues on osx. See branch ci/pypy3 . This might require some more investigation before we drop python 2.7.

**Comment by marcogario** [comment]
With #510 we confirmed that pypy3.5 works fine. This removes my last doubt on dropping 2.7. Version 0.8.0 will be the last one supporting 2.7.

**Comment by marcogario** [comment]
Dropping support for python 2 in 0.9.0. See https://github.com/pysmt/pysmt/pull/635
