### ISSUE TITLE
Mathsat installation on MacOS

### ISSUE THREAD

**Issue by cristian-mattarei** [pysmt/pysmt#519]
``pysmt-install --msat`` does not work on MacOS (with the pip package). It does work on the master branch if you clone and install pysmt directly from https://github.com/pysmt/pysmt

**Comment by marcogario** [comment]
What is the error?

**Comment by marcogario** [comment]
Is this related to #518 ?

**Comment by marcogario** [comment]
Closing since we cannot reproduce.
