### ISSUE TITLE
issues installing CVC4 on Mac OS X

### ISSUE THREAD

**Issue by rhishi** [pysmt/pysmt#52]
I'm wondering if you guys have tried pysmt-install on Mac OS X. I tried installing CVC4, MathSAT, and ran into very obvious issues. Good news is I was able to fix most of these issues. Here's a list of issues/fixes for CVC4. I'll write later about MathSAT.

My environment:
* Mac OS X Yosemite 10.10.2
* Anaconda Python 2.7.9
* Homebrew to install non-python packages

pysmt-install --cvc4 first gave me obvious problems, because I didn't even have autoconf/automake etc. 

To fix that I did:
```
brew install autoconf
brew install automake
brew install libtool
brew install boost
brew install swig
brew install gmp
```
I installed Java JRE, JDK from Oracle. That's needed for running antlr used by CVC4.

I got a warning about libtoolize & glibtoolize, so I followed the advice by doing:
```
ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
```

GMP could not be found even if it was in /usr/local. So I did:
```
setenv LDFLAGS /usr/local/lib
setenv CPPFLAGS /usr/local/include
```

**Suggestion:** Add the above as manual setup instructions before trying to install CVC4.

-----------
pysmt-install --cvc4 then gave a error of `cvc4_wrapper.patch` not found. I just ignored the error, and continued. The rest of the text below is with that situation. Now after doing everything I realize that the patch fixes one of the swig problems (but doesn't seem to fix the problems I list below).

The reason why the patch isn't found is because the patch is missing in the pypi tarball or the installed files. I see it in the github tarball.

**Suggestion:** make sure to distribute the solver install patches!

--------------
pysmt-install --cvc4 then went through the steps of get-antlr, configure, make, and then I got a simple error:
```
mv: rename .libs/CVC4.so.3.0.0 to ./_CVC4.so: No such file or directory
```

That "mv" command is invoked by install.py, and in my build there was no `.libs/CVC4.so.3.0.0`, but I had `.libs/CVC4.so` symlinked to `.libs/CVC4.3.so`.

So I changed the "mv" command to `ln -s .libs/CVC4.so _CVC4.so`.

Then the install succeeded, but the resultant CVC4 module didn't work. When I did "import CVC4", I got a swig dlopen import error regarding `libcvc4.3.dylib`. So I found and symlinked that too.

But, all shared libraries of CVC4 have the install-prefix embedded in them. By default it is /usr/local. That is confirmed by running otool:
```
[prompt] otool -L builds/src/bindings/python/.libs/CVC4.so
builds/src/bindings/python/.libs/CVC4.so:
	/usr/local/lib/libcvc4.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/local/lib/libcvc4parser.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/local/lib/libgmp.10.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)	

[prompt] otool -L builds/lib/libcvc4.3.dylib
builds/lib/libcvc4.3.dylib:
	/usr/local/lib/libcvc4.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/local/lib/libgmp.10.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

So, even if the .so or .dylib are symlinked in the directory containing CVC4.py, there is still an import error.

**Suggestion:** please add `--prefix` when configuring CVC4, and do make; make install. That way, all libs are in the right place. You could have two folders `source` and `install`. The former is used to unzip and build the source code, while the latter is used as the install prefix. This way, it's easier to delete the full source/build folder tree, and have just the install folder.

---------------

After all of the above, I was able to get `python -c 'import CVC4'` to load all the libs correctly. But then I got an undefined symbol error:

```
Symbol not found: __ZN4CVC411ExprManager7mkConstINS_12TypeConstantEEENS_4ExprERKT_
```

Looks like CVC4's swig-generated python interface isn't really completely correct. I was able to fix the above error by commenting out a line in `expr_manager.i`. Then I got another such error regarding `__ZNK4CVC44Expr8getConstINS_12TypeConstantEEERKT_v`. So I commented out a line in `expr.i`.

After that, I was finally able to successfully execute `import CVC4` in python. Using it via pysmt worked too!

**Comment by marcogario** [comment]
Hi,

Thanks for the detailed report! Please let us know what issues did you face with Mathsat.

We never tested on Mac OS X, but from what you describe most of the problems are not specific to it, so I think we can easily address/fix most of them.

For what concerns external dependencies of the solvers we need to find a way to provide this information without having to repeat it ourselves, that I think is prone to problems. Maybe a link to the instructions provided by each solver would be a good compromise?
A _very rough_ list of dependencies for building the solvers can be found in the script shippable.sh. That is the script we use in our Continuous Integration system to install the dependencies; however, the whole flow is based on a Ubuntu base system.

Finally, would you mind attaching/sending us a diff of expr_manager.i and expr.i ? 

Thanks again!

**Comment by marcogario** [comment]
Summary:

- Patches are not included in pypi package
- Instructions of dependencies for each solver are not clear
- CVC4 installation could be split to provide binaries in ad-hoc dir

**Comment by marcogario** [comment]
CVC4 Installation uses --prefix in PR #59.
