### ISSUE TITLE
read_smtlib throws exceptions

### ISSUE THREAD

**Issue by nafur** [pysmt/pysmt#525]
I try to call `read_smtlib()` on a file with the following content:

> (set-logic QF_NRA)
> (declare-fun x () Real)
> (assert (< (* x x) 1))
> (assert (> x 1))
> (check-sat)

Unfortunately it fails, though this example does not contains any of the weird smtlib constructs. The out is as follows:

> $ python3 -c "from pysmt.shortcuts import read_smtlib ; read_smtlib(\"hong_1.smt2\")"
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 218, in create_generator
>     c = next(reader)
> StopIteration
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/lib/python3.7/site-packages/pysmt/shortcuts.py", line 1185, in read_smtlib
>     return pysmt.smtlib.parser.get_formula_fname(fname)
>   File "/usr/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 84, in get_formula_fname
>     return get_formula_strict(script, environment)
>   File "/usr/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 76, in get_formula_strict
>     script = parser.get_script(script_stream)
>   File "/usr/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 834, in get_script
>     for cmd in self.get_command_generator(script):
>   File "/usr/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 848, in get_command_generator
>     for cmd in self.get_command(tokens):
>   File "/usr/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 1068, in get_command
>     self.consume_opening(tokens, "<main>")
>   File "/usr/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 1025, in consume_opening
>     p = tokens.consume()
>   File "/usr/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 189, in consume_token
>     return next(self.generator)
> RuntimeError: generator raised StopIteration

This is with the latest pysmt version installed via pip:

> $ pip show pysmt
> Name: PySMT
> Version: 0.7.5
> Summary: A solver-agnostic library for SMT Formulae manipulation and solving
> Home-page: http://www.pysmt.org
> Author: PySMT Team
> Author-email: info@pysmt.org
> License: APACHE
> Location: /usr/lib/python3.7/site-packages
> Requires: six
> Required-by:

**Comment by marcogario** [comment]
This is due to python 3.7. We have a patch that should be working, and are waiting to merge it in. Feel free to try it out #521 .
