### ISSUE TITLE
Formula containing Division term between two variables is not part of QF_NRA.  

### ISSUE THREAD

**Issue by ahmed-irfan** [pysmt/pysmt#537]
In the examples.py
https://github.com/pysmt/pysmt/blob/638e49656f6a70712e37fcaca0e0f417b8d1a456/pysmt/test/examples.py#L880

**Comment by mikand** [comment]
Are you sure?  The "Reals" theory that is defined here: http://smtlib.cs.uiowa.edu/theories-Reals.shtml seems to allow for division and QF_NRA is defined as the QF logic over the whole "Reals"...

**Comment by ahmed-irfan** [comment]
I think this issue is beyond the scope of pysmt. Though it is still unclear to me why "/" is part of the QF_NRA.
We can discuss this issue offline.
