### ISSUE TITLE
yices ef-solve

### ISSUE THREAD

**Issue by gitsper** [pysmt/pysmt#540]
Are there any plans to implement Exists ForAll as is described in [this](http://smt2015.csl.sri.com/wp-content/uploads/2015/06/2015-Dutertre-Solving-Exists-Forall-Problems-With-Yices.pdf) yices whitepaper? The yices EF solver is purportedly the best available, but trying to solve a formula with a single outer `ForAll` with `solver_name='yices'` raises the error: "NoSolverAvailableError: Solver 'yices' does not support logic LIA". It's true that yices doesn't support LIA, but it does support a subset of LIA, namely EF problems. Any thoughts on how to recognize formulas that are EF and then solve them using yices's `ef-solve` method?

**Comment by gitsper** [comment]
So according to [this](https://github.com/SRI-CSL/yices2/issues/86) open issue in the yices project, the yices python api does not import the yices exists-forall solver. Thank you for your advice, I wasn't aware I could just get ahold of the underlying solver as in the allsat.py example. So I guess my next step is to get in touch with the yices folks and see what can be done to include the exists-forall solver in the yices python api so that I can access it directly.

Thank you!

**Comment by gitsper** [comment]
On the other hand, would there be some way to use the smt-lib module provided by pysmt? In yices, I can define my model in smt-lib and then at the end of the model append
```
(ef-solve)
(show-model)
```
And running this script with `/path/to/yices --mode='ef' model.yices` would print the model to stdout. Is there a way I can modify the [generic smtlib](https://github.com/pysmt/pysmt/blob/master/examples/generic_smtlib.py) example to achieve this?

**Comment by marcogario** [comment]
Please note that we do not use the official python API, because that is quite recent and we have not gotten around to adapt our code. We use our own wrapper called yicespy [1]. This is a very simple wrapper: if there is a method in the C API, this also is available in the python wrapper. My understanding of the issue that you linked is that this is not available also in the C API.

Extending the smt-lib module would probably be the easiest way. Take a look at SmtLibSolver at https://github.com/pysmt/pysmt/blob/master/pysmt/smtlib/solver.py#L67 . Just create a subclass that implements the ```ef-solve`` command (see how the solve() function is defined there). That should be all that is needed. 

If you do, and it works, please consider opening a PR to include this as an extension of yices.

[1] https://github.com/pysmt/yicespy

**Comment by gitsper** [comment]
Ok, I agree extending the smt-lib module is the best way. I will open a PR if I get anything working :+1: Thanks!

**Comment by marcogario** [comment]
What is the status of this? If you have some working application code, I would be glad to support you in completing this feature and submit a PR.

**Comment by gitsper** [comment]
So a quick update-- I proceeded by trying to add yices as a SmtLibSolver. yices-smt2 reports things that pysmt does not expect to receive, i.e. `(add-constraint ...)` causing some parsing errors.  The only other issue I had is that yices then wouldn't solve problems that I knew that z3 could solve. I'll look into it further and report if I get it working.

**Comment by marcogario** [comment]
Hi! 

I do not see a way forward for this issue. I will close it for now. If you think some action on our side is needed, feel free to re-open it.

Thanks!
