### ISSUE TITLE
read_smtlib not working anymore using python 3.7

### ISSUE THREAD

**Issue by samuelkolb** [pysmt/pysmt#551]
Steps to reproduce the error:
- run python 3.7
- download (as file.smt2) e.g. https://clc-gitlab.cs.uiowa.edu:2443/SMT-LIB-benchmarks/QF_LRA/raw/master/2017-Heizmann-UltimateInvariantSynthesis/_array1.i_3_2_2.bpl_11.smt2
- pysmt.shortcuts.read_smtlib(file.smt2)

_Originally posted by @samuelkolb in https://github.com/pysmt/pysmt/issues/488#issuecomment-453482349_

**Comment by mikand** [comment]
@samuelkolb This issue seems fixed on the master branch of pysmt (I just tried on my machine).
Which version are you using?

**Comment by samuelkolb** [comment]
@mikand I'm using a fresh install from PyPi, version 0.7.5, I'm guessing the fix is not included in there yet? Would it be possible to include?
