### ISSUE TITLE
Continuous Delivery for dev versions 

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#556]
Seems like I have been falling behind on making release, due to external commitments. The proposal is to extend travis to perform continuous delivery of the dev versions.

If the test on master pass, travis should pack the release and upload it to pypi. This would make it possible for people to pip install the latest version using the --dev flag.

Main release still will have to be made manually, but this is probably ok, since we want to prepare release notes etc.

**Comment by marcogario** [comment]
We might consider moving the CI to Azure pipelines, to consolidate the testing for the 3 platforms in one place.

https://azure.microsoft.com/en-us/services/devops/pipelines/

**Comment by marcogario** [comment]
In the current CI we do the following:
- Test the python versions: 2.7, 3.7, pypy3.5, pypy
- Test on Ubuntu Xenial, OS X 10.13, Windows (unspecified - 8?)
- On non-master commits we run only Linux / py 3.7, without the ALL solvers configuration
- Coverage is (supposedly) executed on master when with the ALL solvers configuration
- On the ALL solvers configuration, we also run the examples/ folder

The main reason for the last 3 points was that we wanted cheap tests to run on non-PR commits. 
Pipelines has a concept of tasks that can be made conditional on each other. This means that we can have a finer breakdown of the activity. The current proposal is  the following:
- Task 1: Linux / python 3.7 / all solvers but not the ALL configuration
- Task 2: Other OS's
-- Linux / python 3.7 / ALL (including coverage)
-- OSX / python 3.7 / all (supported) solvers
-- Windows / python 3.7 / all (supported) solvers
- Task 3: Cython and GMPY
-- Linux / python 3.7 / PYSMT_SOLVER=None CYTHON
-- Linux / python 3.7 / PYSMT_SOLVER=None GMPY   
-- Linux / python 3.7 / PYSMT_SOLVER=None CYTHON and GMPY
- Task 4: pypy35
-- Linux / pypy35 / PYSMT_SOLVER=None
-- Windows / pypy35 / PYSMT_SOLVER=None
-- OSX / pypy35 / PYSMT_SOLVER=None
- Task 5: Linux / python 2.7
- Task 6: Upload to PyPi.

Tasks 2-5 will be enabled only on master or PR.
Task 6 will only execute on master.

Another feature from pipelines is the availability of Artifacts that can be used to store intermediate results. To investigate how we could leverage this to cache solvers.

**Comment by mikand** [comment]
I started working a bit on this, with some initial success in #564. Still quite some work to do...

**Comment by marcogario** [comment]
What is the status of this? did you follow the job breakdown as described above? If so, are any of these complete?

**Comment by mikand** [comment]
So, I followed your schema (but I kept python 2.7 for all the tests for now). Everything is now working except for pypy (that is currently not natively supported by azure-pipelines and currently requires some workarounds, see https://github.com/Microsoft/azure-pipelines-tasks/issues/8514). Moreover, we still lack Job 6.

IMHO, we can add pypy and then port azure pipelines to master. Job 6 can be handles in a separate PR. What do you think?

**Comment by mikand** [comment]
BTW, I believe you have access to the azuer account I created for pysmt, right?
https://dev.azure.com/micheliandrea/PySMT/_build?definitionId=1

**Comment by marcogario** [comment]
I have access to the azure account.

Ok with post-poning Job 6. In the meanwhile, can you create an account for pypi?I will try to see if I can add you as admin for pySMT.

The idea of puttin 2.7 in a dedicated job was to speed up the CI. However, I think the sooner we get rid of  2.7, the better... Therefore, for pypy, don't spend time on pypy2.7, let's focus on pypy35.

**Comment by mikand** [comment]
OK. I finished adding pypy and the current configuration should reflect the structure above (except for job 6)

Here is an example of a normal branch build: https://dev.azure.com/micheliandrea/PySMT/_build/results?buildId=62
Here is an example of a PR/master build: https://dev.azure.com/micheliandrea/PySMT/_build/results?buildId=63

In my opinion we can switch to azure now.

**Comment by marcogario** [comment]
#571 uploads every version from master into the test.pypi. I would let this work for a few weeks, and if we do not experience any problem, we can change the repo to the real pypi.

**Comment by marcogario** [comment]
#579 Fixes the last issue with uploading to pypi.
We can now install pre-releases with `pip install pysmt --pre`. 

I tried it, and run the tests, checked solvers versions, and check pysmt version and everything seems to work! :)

**Comment by mikand** [comment]
:+1: :+1: :+1:
