### ISSUE TITLE
StrIndexof Typo in simplifier.py

### ISSUE THREAD

**Issue by rodamber** [pysmt/pysmt#563]
Hi, everyone.

I believe there's a typo here:

https://github.com/pysmt/pysmt/blob/6be9413fb14509c2af05427c0402fe4c87363626/pysmt/simplifier.py#L896

Shouldn't it be 'StrIndexOf' instead?

Thanks.

**Comment by marcogario** [comment]
That seems to be the case. Can you add a test case to reproduce the issue? Thanks

**Comment by marcogario** [comment]
See #569 . Thanks for reporting the issue.
