### ISSUE TITLE
Python -m pysmt install

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#572]
We should enable this, to make it easier to see which version of python is being used.

**Comment by mikand** [comment]
:+1:

**Comment by marcogario** [comment]
I removed the pysmt and pysmt-shell scripts form setup.py. I think nobody is using them, and it does not make sense to pollute the bin folder with this.

`python -m pysmt install` and `python -m pysmt shell` are both working. We might consider breaking down the shell into the solver proxy and the shell itself (option --interactive). 

See branch i572/pysmt_module

**Comment by marcogario** [comment]
see #573
