### ISSUE TITLE
Failed installation of btor

### ISSUE THREAD

**Issue by muchang** [pysmt/pysmt#580]
Commandline:
```
 pysmt-install --btor
```
Log:
```
fatal: destination path './deps/lingeling' already exists and is not an empty directory.
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -c lglib.c
lglib.c: In function ‘lglstampall’:
lglib.c:19233:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if (rootsonly) noimpls++; goto CONTINUE;
  ^~
lglib.c:19233:28: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if (rootsonly) noimpls++; goto CONTINUE;
                            ^~~~
rm -f lglcflags.h
echo '#define LGL_CC "gcc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0"' >> lglcflags.h
echo '#define LGL_CFLAGS "-Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA"' >> lglcflags.h
rm -f lglcfg.h
./mkconfig.sh > lglcfg.h
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -c lglbnr.c
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -c lgldimacs.c
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -c lglopts.c
ar rc liblgl.a lglib.o lglbnr.o lgldimacs.o lglopts.o 
ranlib liblgl.a
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -c lglmain.c
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -o lingeling lglmain.o -L. -llgl -lm
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -c plingeling.c
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -pthread -o plingeling plingeling.o -L. -llgl -lm
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -c ilingeling.c
ilingeling.c: In function ‘progress’:
ilingeling.c:212:23: warning: ‘%d’ directive writing between 1 and 10 bytes into a region of size 6 [-Wformat-overflow=]
   sprintf (fmt, "c %%0%dd", i);
                       ^~
ilingeling.c:212:17: note: directive argument in the range [1, 2147483646]
   sprintf (fmt, "c %%0%dd", i);
                 ^~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from lglib.h:8,
                 from ilingeling.c:5:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 7 and 16 bytes into a destination of size 10
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -pthread -o ilingeling ilingeling.o -L. -llgl -lm
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -c treengeling.c
treengeling.c: In function ‘mysrand’:
treengeling.c:1381:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
   if (!z) z = ~z; if (!w) w = ~w;
   ^~
treengeling.c:1381:19: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
   if (!z) z = ~z; if (!w) w = ~w;
                   ^~
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -pthread -o treengeling treengeling.o -L. -llgl -lm
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -c lglmbt.c
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -o lglmbt lglmbt.o -L. -llgl -lm
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -c lgluntrace.c
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -o lgluntrace lgluntrace.o -L. -llgl -lm
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -c lglddtrace.c
gcc -Wall -O3 -fPIC -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLDRUPLIG -DNLGLYALSAT -DNLGLFILES -DNLGLDEMA -o lglddtrace lglddtrace.o -L. -llgl -lm
fatal: destination path './deps/btor2tools' already exists and is not an empty directory.
gcc -W -Wall -Wextra -Wredundant-decls -std=gnu99 -fPIC -O3 -DNDEBUG
makefile generated
mkdir -p build
mkdir -p bin
gcc -W -Wall -Wextra -Wredundant-decls -std=gnu99 -fPIC -O3 -DNDEBUG -o build/btor2parser.o -c src/btor2parser/btor2parser.c -Isrc
gcc -W -Wall -Wextra -Wredundant-decls -std=gnu99 -fPIC -O3 -DNDEBUG -o build/btorsimrng.o -c src/btorsim/btorsimrng.c -Isrc/btorsim
gcc -W -Wall -Wextra -Wredundant-decls -std=gnu99 -fPIC -O3 -DNDEBUG -o build/btorsimbv.o -c src/btorsim/btorsimbv.c -Isrc
ar rc build/libbtor2parser.a build/btor2parser.o
gcc -W -Wall -Wextra -Wredundant-decls -std=gnu99 -fPIC -O3 -DNDEBUG -o build/catbtor.o -c src/catbtor.c -Isrc
ranlib build/libbtor2parser.a
gcc -W -Wall -Wextra -Wredundant-decls -std=gnu99 -fPIC -O3 -DNDEBUG -o build/btorsim.o -c src/btorsim/btorsim.c -Ibtorsim -Isrc
gcc -W -Wall -Wextra -Wredundant-decls -std=gnu99 -fPIC -O3 -DNDEBUG -o bin/catbtor build/catbtor.o -Lbuild -lbtor2parser
gcc -W -Wall -Wextra -Wredundant-decls -std=gnu99 -fPIC -O3 -DNDEBUG -o bin/btorsim build/btorsim.o build/btorsimbv.o build/btorsimrng.o -Lbuild -lbtor2parser
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- LIB directory is '/home/zhangche/.smt_solvers/btor/boolector-8062caf14f797a3aa85bf310705973468874e127/build/lib'
-- BIN directory is '/home/zhangche/.smt_solvers/btor/boolector-8062caf14f797a3aa85bf310705973468874e127/build/bin'
-- Found PythonInterp: /home/zhangche/miniconda3/envs/smtfuzz/bin/python (found version "3.7.3") 
-- Found PythonLibs: /home/zhangche/miniconda3/envs/smtfuzz/lib (found suitable version "3.7.3", minimum required is "3.7") 
-- Performing Test HAVE_FLAG_fPIC
-- Performing Test HAVE_FLAG_fPIC - Success
-- Configuring with C flag '-fPIC'
-- Configuring with CXX flag '-fPIC'
-- Performing Test HAVE_FLAG_std_gnu99
-- Performing Test HAVE_FLAG_std_gnu99 - Success
-- Configuring with C flag '-std=gnu99'
-- Configuring with CXX flag '-std=gnu++11'
-- Performing Test HAVE_FLAG_W
-- Performing Test HAVE_FLAG_W - Success
-- Configuring with C flag '-W'
-- Configuring with CXX flag '-W'
-- Performing Test HAVE_FLAG_Wall
-- Performing Test HAVE_FLAG_Wall - Success
-- Configuring with C flag '-Wall'
-- Configuring with CXX flag '-Wall'
-- Performing Test HAVE_FLAG_Wextra
-- Performing Test HAVE_FLAG_Wextra - Success
-- Configuring with C flag '-Wextra'
-- Configuring with CXX flag '-Wextra'
-- Performing Test HAVE_FLAG_Wredundant_decls
-- Performing Test HAVE_FLAG_Wredundant_decls - Success
-- Configuring with C flag '-Wredundant-decls'
-- Configuring with CXX flag '-Wredundant-decls'
-- No build type set, options are: Debug;Release
-- Building Release build
-- Performing Test HAVE_FLAG_O3
-- Performing Test HAVE_FLAG_O3 - Success
-- Configuring with C flag '-O3'
-- Configuring with CXX flag '-O3'
-- Performing Test HAVE_SIGNALS
-- Performing Test HAVE_SIGNALS - Success
-- Performing Test HAVE_TIME_UTILS
-- Performing Test HAVE_TIME_UTILS - Success
-- Found Btor2Tools: /home/zhangche/.smt_solvers/btor/boolector-8062caf14f797a3aa85bf310705973468874e127/deps/btor2tools/src  
-- Found Btor2Tools library: /home/zhangche/.smt_solvers/btor/boolector-8062caf14f797a3aa85bf310705973468874e127/deps/btor2tools/build/libbtor2parser.a
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found Lingeling: /home/zhangche/.smt_solvers/btor/boolector-8062caf14f797a3aa85bf310705973468874e127/deps/lingeling  
-- Found Lingeling library: /home/zhangche/.smt_solvers/btor/boolector-8062caf14f797a3aa85bf310705973468874e127/deps/lingeling/liblgl.a
-- Could NOT find CaDiCaL (missing: CaDiCaL_INCLUDE_DIR CaDiCaL_LIBRARIES) 
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Found PythonLibs: /home/zhangche/miniconda3/envs/smtfuzz/lib (found version "3.7.3") 
-- Found Cython: /home/zhangche/miniconda3/envs/smtfuzz/bin/cython  
-- Configuring done
WARNING: Target "pyboolector" requests linking to directory "/home/zhangche/miniconda3/envs/smtfuzz/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pyboolector" requests linking to directory "/home/zhangche/miniconda3/envs/smtfuzz/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/zhangche/.smt_solvers/btor/boolector-8062caf14f797a3aa85bf310705973468874e127/build
[  1%] Generate pyboolector_options.pxd
Scanning dependencies of target boolector
[  1%] Built target pyboolector_options
[  1%] Building C object src/CMakeFiles/boolector.dir/btorcore.c.o
[  3%] Building C object src/CMakeFiles/boolector.dir/parser/btorbtor2.c.o
/home/zhangche/.smt_solvers/btor/boolector-8062caf14f797a3aa85bf310705973468874e127/src/parser/btorbtor2.c: In function ‘parse_btor2_parser’:
/home/zhangche/.smt_solvers/btor/boolector-8062caf14f797a3aa85bf310705973468874e127/src/parser/btorbtor2.c:324:12: error: ‘BTOR2_TAG_ne’ undeclared (first use in this function); did you mean ‘BTOR2_TAG_one’?
       case BTOR2_TAG_ne:
            ^~~~~~~~~~~~
            BTOR2_TAG_one
/home/zhangche/.smt_solvers/btor/boolector-8062caf14f797a3aa85bf310705973468874e127/src/parser/btorbtor2.c:324:12: note: each undeclared identifier is reported only once for each function it appears in
src/CMakeFiles/boolector.dir/build.make:998: recipe for target 'src/CMakeFiles/boolector.dir/parser/btorbtor2.c.o' failed
make[2]: *** [src/CMakeFiles/boolector.dir/parser/btorbtor2.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:164: recipe for target 'src/CMakeFiles/boolector.dir/all' failed
make[1]: *** [src/CMakeFiles/boolector.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/zhangche/miniconda3/envs/smtfuzz/bin/pysmt-install", line 10, in <module>
    sys.exit(main())
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/pysmt/cmd/install.py", line 261, in main
    installer.install(force_redo=options.force_redo)
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/pysmt/cmd/installers/base.py", line 149, in install
    self.compile()
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/pysmt/cmd/installers/btor.py", line 69, in compile
    directory=os.path.join(self.extract_path, "build"))
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/pysmt/cmd/installers/base.py", line 231, in run
    cwd=directory, stderr=stderr)
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j2']' returned non-zero exit status 2.
```
Environment:
Ubuntu:18.04
Python: 3.7
Cython: 0.29.7

**Comment by marcogario** [comment]
Which version of pysmt are you using? Can you try master?

**Comment by muchang** [comment]
I was using pysmt-0.8.0, installed by pip. Maybe I should try the latest version on github.

**Comment by muchang** [comment]
I used the script 'install.py' in the master branch with the commandline:
'''
python install.py --btor
'''
Then I failed with the Logs:
'''
[ 96%] Building CXX object src/api/python/CMakeFiles/pyboolector.dir/pyboolector.cxx.o
In file included from /home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/Python.h:137:0,
                 from /home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:4:
/home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/modsupport.h:50:24: warning: redundant redeclaration of ‘PyObject* _Py_BuildValue_SizeT(const char*, ...)’ in same scope [-Wredundant-decls]
 PyAPI_FUNC(PyObject *) _Py_BuildValue_SizeT(const char *, ...);
                        ^~~~~~~~~~~~~~~~~~~~
/home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/modsupport.h:20:41: note: previous declaration of ‘PyObject* _Py_BuildValue_SizeT(const char*, ...)’
 #define Py_BuildValue                   _Py_BuildValue_SizeT
                                         ^
/home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/modsupport.h:49:24: note: in expansion of macro ‘Py_BuildValue’
 PyAPI_FUNC(PyObject *) Py_BuildValue(const char *, ...);
                        ^~~~~~~~~~~~~
In file included from /home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/Python.h:147:0,
                 from /home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:4:
/home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/abstract.h:320:24: warning: redundant redeclaration of ‘PyObject* _PyObject_CallFunction_SizeT(PyObject*, const char*, ...)’ in same scope [-Wredundant-decls]
 PyAPI_FUNC(PyObject *) _PyObject_CallFunction_SizeT(PyObject *callable,
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/abstract.h:139:33: note: previous declaration of ‘PyObject* _PyObject_CallFunction_SizeT(PyObject*, const char*, ...)’
 #  define PyObject_CallFunction _PyObject_CallFunction_SizeT
                                 ^
/home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/abstract.h:296:24: note: in expansion of macro ‘PyObject_CallFunction’
 PyAPI_FUNC(PyObject *) PyObject_CallFunction(PyObject *callable,
                        ^~~~~~~~~~~~~~~~~~~~~
/home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/abstract.h:324:24: warning: redundant redeclaration of ‘PyObject* _PyObject_CallMethod_SizeT(PyObject*, const char*, const char*, ...)’ in same scope [-Wredundant-decls]
 PyAPI_FUNC(PyObject *) _PyObject_CallMethod_SizeT(PyObject *obj,
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/abstract.h:140:31: note: previous declaration of ‘PyObject* _PyObject_CallMethod_SizeT(PyObject*, const char*, const char*, ...)’
 #  define PyObject_CallMethod _PyObject_CallMethod_SizeT
                               ^
/home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/abstract.h:308:24: note: in expansion of macro ‘PyObject_CallMethod’
 PyAPI_FUNC(PyObject *) PyObject_CallMethod(PyObject *obj,
                        ^~~~~~~~~~~~~~~~~~~
/home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/abstract.h:330:24: warning: redundant redeclaration of ‘PyObject* _PyObject_CallMethodId_SizeT(PyObject*, _Py_Identifier*, const char*, ...)’ in same scope [-Wredundant-decls]
 PyAPI_FUNC(PyObject *) _PyObject_CallMethodId_SizeT(PyObject *obj,
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/abstract.h:142:36: note: previous declaration of ‘PyObject* _PyObject_CallMethodId_SizeT(PyObject*, _Py_Identifier*, const char*, ...)’
 #    define _PyObject_CallMethodId _PyObject_CallMethodId_SizeT
                                    ^
/home/parallels/miniconda3/envs/smtfuzz/include/python3.7m/abstract.h:315:24: note: in expansion of macro ‘_PyObject_CallMethodId’
 PyAPI_FUNC(PyObject *) _PyObject_CallMethodId(PyObject *obj,
                        ^~~~~~~~~~~~~~~~~~~~~~
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx: In function ‘void __Pyx__ExceptionSave(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx: In function ‘void __Pyx__ExceptionSave(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54505:21: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     *type = tstate->exc_type;
                     ^~~~~~~~
                     curexc_type
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54506:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     *value = tstate->exc_value;
                      ^~~~~~~~~
                      curexc_value
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54507:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     *tb = tstate->exc_traceback;
                   ^~~~~~~~~~~~~
                   curexc_traceback
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx: In function ‘void __Pyx__ExceptionReset(PyThreadState*, PyObject*, PyObject*, PyObject*)’:
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54514:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tmp_type = tstate->exc_type;
                        ^~~~~~~~
                        curexc_type
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54515:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tmp_value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54516:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tmp_tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54517:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tstate->exc_type = type;
             ^~~~~~~~
             curexc_type
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54518:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tstate->exc_value = value;
             ^~~~~~~~~
             curexc_value
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54519:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tstate->exc_traceback = tb;
             ^~~~~~~~~~~~~
             curexc_traceback
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx: In function ‘int __Pyx__GetException(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54574:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tmp_type = tstate->exc_type;
                        ^~~~~~~~
                        curexc_type
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54575:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tmp_value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54576:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tmp_tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54577:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tstate->exc_type = local_type;
             ^~~~~~~~
             curexc_type
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54578:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tstate->exc_value = local_value;
             ^~~~~~~~~
             curexc_value
/home/parallels/.smt_solvers/btor/boolector-f689fbbfe820392d35e26be368f9d87d2dbdb037/build/src/api/python/pyboolector.cxx:54579:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tstate->exc_traceback = local_tb;
             ^~~~~~~~~~~~~
             curexc_traceback
'''

**Comment by marcogario** [comment]
Do you manage to install boolector directly? Ie by downloading the sources from their github and compiling it? If yes, that is a problem for us. Otherwise you should report this to boolector.

**Comment by muchang** [comment]
Thank you for your comments! I downloaded the sources from their GitHub and was able to compile successfully without error. It might be a problem for pysmt.

**Comment by marcogario** [comment]
:disappointed: that is unfortunate. Thanks for investigating further, we will look into this.

**Comment by marcogario** [comment]
Note that if you installed boolector from the sources, you should be able to use pysmt with it. Just make sure the python bindings for boolector are in your python path, and pysmt will detect that it is installed.

**Comment by marcogario** [comment]
Can you confirm that the version of cython from miniconda (/home/zhangche/miniconda3/envs/smtfuzz/bin/cython) ?

I seem to be able to reproduce and I identified 2 issues. The first one does not apply to you, but will start a PR to fix it soon. The second was about incompatible version of Cython.
After doing `python -m pip install cython` and ensuring that the cython that I was using was the one 0.29.7, the build seems to succeed.

**Comment by muchang** [comment]
Thank you for your investigation and fixed.
The version of cython from my miniconda is 0.29.7, same as yours.

I tried PR #581 and it works!
This issue could be closed by PR #581.
Thanks again for your help.

**Comment by hadipourh** [comment]
I think this problem still persists ...
I tried `pysmt-install --btor` command with the following setup:
```
Linux 92da30ebd49d 6.10.14-linuxkit #1 SMP Mon Feb 24 16:35:16 UTC 2025 aarch64 aarch64 aarch64 GNU/Linu
Python 3.12.3
Cython version 3.0.12
```

**Comment by mikand** [comment]
@hadipourh Can you past the output of pysmt-install? The issue was closed in 2019, very likely your problem is different 😄

**Comment by hadipourh** [comment]
I was installing it in a debian linux container hosted on a macOS.
However, when I switched to an independent debian-based Linux, the problem was resolved. I guess there was something wrong with my setup. Sorry!
