### ISSUE TITLE
Function names quoted with ' instead of | when seraializing to smt2

### ISSUE THREAD

**Issue by ekiwi** [pysmt/pysmt#584]
A short example:
```.py
from pysmt.shortcuts import *
f_t = FunctionType(BOOL, [BOOL])
f0 = Symbol('f 0', f_t)
f0_of_false = Function(f0, [Bool(False)])
to_smtlib(f0_of_false, False)
```

The last expression results in the string: `"('f 0' false)"`
The expected result would be: `'(|f 0| false)'`

I can get the expected result by changing [pysmt/smtlib/printers.py#L94](https://github.com/pysmt/pysmt/blob/142d66196961fee56281cf458147362dcad3c000/pysmt/smtlib/printers.py#L94) to:
```.py
return self.walk_nary(formula, quote(formula.function_name().symbol_name()))
```

However, I am not sure if that is a valid fix.

**Comment by mikand** [comment]
@ekiwi Thanks for reporting this. Indeed you are right and pysmt/smtlib/printers.py#L94 should be changed as you suggest. I'll do it right away.

**Comment by mikand** [comment]
This is now fixed in master. If you are using pysmt using `pip` you can installa pre-release package with 
`pip install --upgrade --pre pysmt`

**Comment by ekiwi** [comment]
That was quick.
Thanks a lot!
