### ISSUE TITLE
Operator overloading

### ISSUE THREAD

**Issue by jarble** [pysmt/pysmt#593]
Currently, it seems that PySMT does not overload Python's logical operators when defining problems to be solved. Without operator overloading, PySMT defines them in this way:

```
problem = And(Equals(sum_hello, sum_world),
              Equals(sum_hello, Int(25)))
```

I'd like to overload the `and` and `or` operators to improve readability, but I'm not sure if this would be possible:

`problem = (sum_hello == sum_world) and (sum_hello == Int(25))`

Would it be feasible to overload Python's built-in operators for PySMT?

**Comment by marcogario** [comment]
Hi, 

Infix notation is available for many operators. && and || are used for And and Or.  We also have fluent notation. The following should both work:

```
problem = (sum_hello.Equals(sum_world)).And(sum_hello.Equals(25))
````

```
sum_hello.Equals(sum_world) && sum_hello.Equals(25)```

The main issue with your example is the overloading of ==. In general, we decided not to support it. If you have suggestions on how to implement this without impacting functionality in which you are interested to check if two Objects are the same (keys in dictionaries, lists etc), please let us know.
