### ISSUE TITLE
Python 3.8 Deprecation Warning for `ABCs` from `collections`

### ISSUE THREAD

**Issue by gilbo** [pysmt/pysmt#600]
I'm getting the following warning on 3.7

```
/usr/local/lib/python3.7/site-packages/pysmt/walkers/generic.py:43: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if len(nodetypes) == 1 and isinstance(nodetypes[0], collections.Iterable):
```

**Comment by marcogario** [comment]
Is this from master or a stable release (via pip)? I thought we had fixed
this.

**Comment by gilbo** [comment]
Ahh, it’s from pip. I should have checked. Sorry.

**Comment by marcogario** [comment]
No worries, and thanks for reporting this! We are kind of super late with the new release... Hopefully, we will get around in the next few weeks.
