### ISSUE TITLE
Symbol (un)quoting

### ISSUE THREAD

**Issue by alebugariu** [pysmt/pysmt#607]
While reading the following input file, the parser replaces the vertical bars from |MultiSet#Card| with quotes 'MultiSet#Card':

```(declare-sort |T@U| 0)
(declare-sort |T@T| 0)
(declare-fun intType () T@T)
(declare-fun type (T@U) T@T)
(declare-fun MapType0Type (T@T T@T) T@T)
(declare-fun MapType0TypeInv0 (T@T) T@T)
(declare-fun |MultiSet#Card| (T@U) Int)

(assert (forall ((s@@5 T@U) ) (! (let ((T@@62 (MapType0TypeInv0 (type s@@5))))
 (=> (= (type s@@5) (MapType0Type T@@62 intType)) (<= 0 (|MultiSet#Card| s@@5))))
 :pattern ( (|MultiSet#Card| s@@5))
)))
(check-sat) 
```

The problem is that if we now try to print the formula to an output file, using script.to_file(), the serialize() method does not always add the vertical bars back, so the result is:
```
(declare-sort T@U 0)
(declare-sort T@T 0)
(declare-fun intType () T@T)
(declare-fun type (T@U) T@T)
(declare-fun MapType0Type (T@T T@T) T@T)
(declare-fun MapType0TypeInv0 (T@T) T@T)
(declare-fun |MultiSet#Card| (T@U) Int)
(declare-fun |P#Q| () Int)
(assert (forall ((s@@5 T@U)) (=> (= (type s@@5) (MapType0Type (MapType0TypeInv0 (type s@@5)) intType)) (<= 0 ('MultiSet#Card' s@@5)))))
(check-sat)
```
which is not syntactically correct. Is there a way to avoid this quoting?
I observed this behavior with pysmt version 0.8.0.

Thanks a lot for your help.

**Comment by mikand** [comment]
Dear Alexandra,

thanks for using pysmt! Have you tried to reproduce this issue on the
master version of pysmt?
This looks suspiciously similar to
https://github.com/pysmt/pysmt/issues/584 that
has been fixed a few months ago.

(You can install a development/pre-release version of pysmt using PIP with
'pip install --pre pysmt')

HTH

A.

**Comment by alebugariu** [comment]
Yes, you are right, with the master version everything works fine.
Thanks a lot and sorry for the duplicated bug report.
