### ISSUE TITLE
Is the Solvers Support table up to date ?

### ISSUE THREAD

**Issue by numairmansur** [pysmt/pysmt#609]
Is this table in readme up to date ?

https://github.com/pysmt/pysmt#solvers-support

**Comment by marcogario** [comment]
It looks roughly up to date. Is there something specific you are looking for? Notice that the table shows the relation of solvers/theories supported by pySMT. The solvers might be able to solve more theories than these. An obvious example is floating point. pySMT has no support for floating point, but many solvers (MathSAT and Z3) do.

Please let me know what you are looking for, in some cases adding support is trivial.

**Comment by numairmansur** [comment]
I was specifically curious if Strings is now supported for Z3 via pySMT.
