### ISSUE TITLE
No effect setting the 'debug_interaction' option in the SmtLibSolver 

### ISSUE THREAD

**Issue by smover** [pysmt/pysmt#615]
When setting the `debug_interaction` option on a SmtLibSolver I get no output of the interaction with the solver. The code I use to reporduce the issue is (substitute the path to mathsat):
```python
from pysmt.logics import QF_LRA
from pysmt.shortcuts import (
    Solver,
    LT,
    Real,
    get_env
)

name = "mathsat-smtlib"
path = [<path to mathsat>]
logics = [QF_LRA]
env = get_env()
env.factory.add_generic_solver(name, path, logics)
solver = Solver(name=name, logic=logics[0], solver_options={'debug_interaction':True})
solver.is_valid(LT(Real(3),Real(5)))
```

The test case in (test_generic_wrapper.py)[https://github.com/pysmt/pysmt/blob/451c1bb5f0162963a09298e2b1f29eb93939cdeb/pysmt/test/smtlib/test_generic_wrapper.py] does not seem to test if the debug really generates the output.

It seems that the option is set in a map but then removed immediately from the map:
https://github.com/pysmt/pysmt/blob/f9a5f113125046601d0a2c6f5c1c8755c3bea2d1/pysmt/smtlib/solver.py#L43

**Comment by mikand** [comment]
See #619
