### ISSUE TITLE
Typo in ITE conversion in the MSatConverter

### ISSUE THREAD

**Issue by smover** [pysmt/pysmt#617]
The implementation if the `walk_ite` conversion in the `MSatConverter` has a typo building the formula for the `nif` part (using the then part of the ite instead of the condition).
The current implementation is:
```python
nif = self.mgr.Not(formula.arg(1))
ni = self.walk_not(nif, [i])
```
While it should be:
```
nif = self.mgr.Not(formula.arg(0))
ni = self.walk_not(nif, [i])
```

This is not a correctness bug since the call to `self.walk_not` still correctly pass `i` as argument and `self.walk_not` does not use the first argument.

**Comment by mikand** [comment]
See #618
