### ISSUE TITLE
Registering New Solver

### ISSUE THREAD

**Issue by cdonovick** [pysmt/pysmt#623]
I am trying to implement a new solver backend.  Implementing that solver / converter / option classes was fairly straight forward (although it would be nice if there was some documentation of the process).  However, what I have not been able to figure out is how to register the solver without needing to fork pysmt and edit `factory.py`.  Is there a method I am missing?

Also if I do edit `factor.py` will the tests automatically run on the new solver?

**Comment by marcogario** [comment]
Sorry for the delayed answer. Right now pySMT allows to register new solvers only via the SMTLIB interface. If you want to integrate at the API level, you need to fork.

The main reason for this is that pysmt is released as a unit with specific versions of solvers. We do not have the capacity to support any version of a solver. Enforcing that the installer, the factory, and the tests have specific solvers and versions makes this simpler.

Tests will run for all solvers in the factory that support certain properties (e.g., if the solver supports LIRA, it will be used for all LIRA tests).
