### ISSUE TITLE
Is there any way to set a time limit for the solving? 

### ISSUE THREAD

**Issue by luosichengx** [pysmt/pysmt#649]
Excuse me, I am working on some challenge scripts, is there any way to set a time limit for the solving?

**Comment by hadipourh** [comment]
Hello!

As far as I know, PySMT does not currently support time_limit parameter. In order to handle this issue, I am using the following code at the moment. Hope PySMT will support time_limit soon. 

```
import time
def reached_time_limit(start_time, timelimit):
    """
    Return True if the timelimit was reached.
    """
    if round(time.time() - start_time) >= timelimit and timelimit != -1:
        print("Reached the time limit of {} seconds".format(timelimit))
        return True
    return False

while not reachedTimelimit(start_time, parameters["timelimit"]):
     #call smt solver here ...
```
Hope that it helps.
