### ISSUE TITLE
Treat BitVectors of length 1 as Bools?

### ISSUE THREAD

**Issue by OppositeNote** [pysmt/pysmt#651]
Hi all,

I'm using bitvectors to model something and would like to use them as "arrays of booleans". What I mean with this is that it would be nice if I could do something like this:

```python
x = Symbol('x', BVType(3))
formula = And(x[0:0], x[1:1], Not(x[2:2]))
is_sat(formula)
```

If I try to do this, pysmt complains that "The formula is not well-formed". I am pretty sure this is because x[0:0] is of course not a boolean, but a bitvector of length 1. So I guess my real question is: Is there a way to convert bitvectors of length 1 to booleans or are there plans to add this feature? I have been looking around the docs, issues and code to find a way but have not yet succeeded.

**Comment by mikand** [comment]
Hi @OppositeNote, thanks for using pysmt!

PySMT is very strict on types to avoid subtle errors in the problem formulation. For this reason, we do not have automatic promotion of BV of length 1 to boolean, but this just means that you need to compare the BV to the constant one to obtain a boolean:

```python
from pysmt.shortcuts import *

def bv2b(x):
    return Equals(x, BVOne(1)) # This function does the conversion, by creating an equality term

x = Symbol('x', BVType(3))
formula = And(bv2b(x[0:0]), bv2b(x[1:1]), Not(bv2b(x[2:2])))
print(is_sat(formula))
```

**Comment by OppositeNote** [comment]
Hi @mikand,

Thank you for the quick answer! I have tested it and it works.
