### ISSUE TITLE
Model incomplete

### ISSUE THREAD

**Issue by rshariffdeen** [pysmt/pysmt#653]
Hi,

When I use the following SMT formula to get a model, the result I get is incomplete

This is the formula:
(set-logic QF_ABV)
(declare-fun arg00 () (Array (_ BitVec 32) (_ BitVec 8)))
(declare-fun arg01 () (Array (_ BitVec 32) (_ BitVec 8)))
(assert (let ((.def_0 (select arg00 #b00000000000000000000000000000000))) (let ((.def_1 ((_ sign_extend 24) .def_0))) (let ((.def_2 (bvadd #b11111111111111111111111111010000 .def_1))) (let ((.def_3 ((_ extract 7 0) .def_2))) (let ((.def_4 ((_ zero_extend 56) .def_3))) (let ((.def_5 ((_ extract 31 0) .def_4))) (let ((.def_6 (bvslt #b00000000000000000000000000000101 .def_5))) (let ((.def_7 (= false .def_6))) (let ((.def_8 (select arg01 #b00000000000000000000000000000001))) (let ((.def_9 ((_ sign_extend 24) .def_8))) (let ((.def_10 (bvadd #b11111111111111111111111111010000 .def_9))) (let ((.def_11 ((_ extract 7 0) .def_10))) (let ((.def_12 ((_ zero_extend 56) .def_11))) (let ((.def_13 (select arg01 #b00000000000000000000000000000000))) (let ((.def_14 ((_ sign_extend 24) .def_13))) (let ((.def_15 (bvadd #b11111111111111111111111111010000 .def_14))) (let ((.def_16 ((_ extract 7 0) .def_15))) (let ((.def_17 ((_ zero_extend 56) .def_16))) (let ((.def_18 (bvmul #b0000000000000000000000000000000000000000000000000000000000001010 .def_17))) (let ((.def_19 (bvadd .def_18 .def_12))) (let ((.def_20 ((_ extract 31 0) .def_19))) (let ((.def_21 (bvslt #b00000000000000000000000000001010 .def_20))) (let ((.def_22 (not .def_21))) (let ((.def_23 (and .def_22 .def_7))) .def_23)))))))))))))))))))))))))
(check-sat)
(get-model)
(exit)

If I used Z3 Clit to get a model, I would get an output such as :

(model 
  (define-fun arg01 () (Array (_ BitVec 32) (_ BitVec 8))
    (lambda ((x!1 (_ BitVec 32))) (ite (= x!1 #x00000001) #x33 #x30)))
  (define-fun arg00 () (Array (_ BitVec 32) (_ BitVec 8))
    ((as const (Array (_ BitVec 32) (_ BitVec 8))) #x32))
)

But pysmt get_model gives me something like:

arg01 := Array{BV{32}, BV{8}}(48_8)[0_32 := 49_8]
arg00 := Array{BV{32}, BV{8}}(48_8)

Is there a mistake I am doing? or is this a bug?

**Comment by mikand** [comment]
Hi @rshariffdeen,

thanks for using pysmt!

The `Array{BV{32}, BV{8}}(48_8)[0_32 := 49_8]` is a string representation of a special object (called ArrayValue) we have in pysmt to represent models for arrays. It is read as "The array with key of type bitvector32 and value bitvector8 that is 48 everywhere except in index 0 where it is 49". You can have as many key := value as you want to specify values of different indexes 

In general you have `Array{<key-type>, <value-type>}(<default_value>)[(<key> := <value>, )*]`

It it something that does not exist in SMTLib, but essentially is a constant of type array.

So, to answer your question, the returned model is complete, it is just represented compactly. 

Does this make sense?

**Comment by rshariffdeen** [comment]
Okay Cool! Yes, this makes sense.
But is there are an efficient way for me to get the values for the arrays, by iterating through the indexes? 
Currently, I don't see how many indexes are in the array either. I tried converting the Array to BV too, it gave me an error stating "unknown width".

**Comment by mikand** [comment]
Sure, 
the following code should be self-explanatory.
```python
from pysmt.shortcuts import *

# Get a model for an array
a = Symbol('a', ArrayType(INT, REAL))
f = And(GT(Select(a, Int(1)), Real(10)),
        LT(Select(a, Int(2)), Real(5)),
        Equals(Select(a, Int(3)), Real(-1)),
        Equals(Select(a, Int(4)), Real(100)))
m = get_model(f)

# Get the array value for a
v = m[a].simplify() # you need this simplify in general
assert v.is_array_value()

# Print the default and assigned values
print('The value of the array a is %s everywhere except:' % v.array_value_default())
avm = v.array_value_assigned_values_map()
for idx, val in avm.items():
    print(' - a[%s] that is %s' % (idx, val))

# One can also access any index value explicitly
print('You can also query for the value of an arbitrary index:')
print(' - a[300] = %s' % v.array_value_get(Int(300)))
print(' - a[1] = %s' % v.array_value_get(Int(1)))
print(' - a[2] = %s' % v.array_value_get(Int(2)))
```

Note that you can also create array values using the `Array()` constructor and use them in formulae:
```python
from pysmt.shortcuts import *

av = Array(INT, Real(0), {Int(1): Real(10)})
a = Symbol('a', ArrayType(INT, REAL))
f = Equals(a, av)
m = get_model(f)
assert m[a].simplify().array_value_get(Int(1)) == Real(10)
```

**Comment by rshariffdeen** [comment]
Thank you very much for the explanation, it cleared a lot of misunderstandings. 
I am still not sure how do we get the correct value without knowing the size of the array, is there a mechanism to get this value? if not I am not clear how to build the correct array even using both array_value_assigned_values_map and array_value_default APIs which only give me half of the information.

**Comment by mikand** [comment]
Ah, sure, we have a function called `array_value_index_type` (https://github.com/pysmt/pysmt/blob/master/pysmt/fnode.py#L633) that will retrieve the type of the array index (BVType(32) in the example below):

```python
from pysmt.shortcuts import *

# Get a model for an array
a = Symbol('a', ArrayType(BVType(32), REAL))
f = And(GT(Select(a, BV(1, 32)), Real(10)),
        LT(Select(a, BV(2, 32)), Real(5)),
        Equals(Select(a, BV(3, 32)), Real(-1)),
        Equals(Select(a, BV(4, 32)), Real(100)))
m = get_model(f)

# Get the array value for a
v = m[a].simplify() # you need this simplify in general
assert v.is_array_value()

assert v.array_value_index_type() == BVType(32)
assert v.array_value_index_type().width == 32
```

**Comment by rshariffdeen** [comment]
thanks a lot for the help

**Comment by rshariffdeen** [comment]
Hi
I cannot figure out the maximum index in the array, can you help out?
For example, if the value map doesn't include the last bit for the array we can assume the value to be default value. However, what is the length of the array?

**Comment by mikand** [comment]
In SMT the arrays are total for the type used as index. For example, an `ArrayType(BVType(32), REAL)` has a length of 2^32 (i.e. maps any bit-vector of size 32 to a REAL). If you have an `ArrayType(INT, REAL)` the size of the array is infinite: it maps any integer to a real.

Note that this is not pysmt-related, it is the way the theory of arrays works: http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf (page 39)
