### ISSUE TITLE
Support of interpolation with Z3, does PySMT support iZ3?

### ISSUE THREAD

**Issue by btwael** [pysmt/pysmt#654]
From the table in README ([https://github.com/pysmt/pysmt#solvers-support](https://github.com/pysmt/pysmt#solvers-support)), PySMT supports interpolation with Z3. However when I tries `pysmt.shortcuts.Interpolator("z3")`, it fails.

Does really PySMT support interpolation with Z3, or do you mean iZ3?

**Comment by mikand** [comment]
We do support interpolation (in the sense of extracting Craig interpolants). Have a look here: https://github.com/pysmt/pysmt/blob/master/pysmt/test/test_interpolation.py

If it does not work, can you provide an example with the expected output?

**Comment by btwael** [comment]
I've contacted `Z3` developers, interpolation is not anymore supported and it will not be back anytime soon.

Interpolation in `pysmt` works fine with MathSAT 5. However there is out there many other SMT-Lib compliant solver with support for interpolation but cannot be used from `pysmt`. From the source code, I didn't see how `pysmt` can extract interpolant via smt-lib.

**Comment by marcogario** [comment]
If things have not changed, interpolation is not part of the SMT-LIB. For MathSAT and Z3 we used to integrate directly at the API level.

There is an extension of the SMT-LIB that seems to be supported by both SMTInterpol and MathSAT https://ultimate.informatik.uni-freiburg.de/smtinterpol/proposal.pdf , but that never made it officially in the SMT-LIB standard. 

Which other solvers did you have in mind? 

We  started supporting things that are extensions of SMT-LIB, most notably the extensions for optimization. Therefore, I would not be against a PR supporting interpolation via SMT-LIB.

**Comment by btwael** [comment]
I was thinking SMTInterpol and [Princess](http://www.philipp.ruemmer.org/princess.shtml). There is also a work around to get interpolant from modern Z3 which I can share with you (privately) from the Z3 developers.

**Comment by marcogario** [comment]
The state of affairs seem to be that most solvers that we currently support do not support this feature. I would be open to accept a PR to support the associated [SMT-LIB extension mentioned](https://github.com/pysmt/pysmt/issues/654#issuecomment-716799157) above.

I will close this issue, as I think the situation has been clarified.
