### ISSUE TITLE
Soft Constraints

### ISSUE THREAD

**Issue by rshariffdeen** [pysmt/pysmt#664]
Hi,
Can we add soft-constraints to a given formula?
Would I be able to get the maximum possible value for a given model instead of just getting a model for a formula?

Thanks!

**Comment by yxliang01** [comment]
They are working on it at #439 . From the comments likes like it can be considered at least alpha version. I am still using z3 for this purpose for my project though. If you give #439 a try, let me know maybe I will consider switching :)

**Comment by marcogario** [comment]
Yes, what @yxliang01 said! :smile: 

I expect things to work for very simple cost functions (like pseudo-boolean optimization). So if this is all you need, it would be great if you could try it out and provide some feedback!

Most of the pending work on the branch is focused on integrating with a solver (OptiMathsat) that should provide significantly better performances than what we have now, and also cover many more interesting optimization problems.

**Comment by rshariffdeen** [comment]
Hi @marcogario @yxliang01 
thanks for the quick reply, I will check this out and update if it worked
but having it in alpha version would mean it is not stable? so I would be hesitant to integrate with my current work. 
I would definitely check it out.

**Comment by marcogario** [comment]
The more feedback and users we get, the faster it gets to a stable state :wink:

**Comment by yxliang01** [comment]
Then, I would recommend releasing an alpha version of it. The more confident the maintainer show and more convenient to use, more users will help testing :)
