### ISSUE TITLE
BDD-based solver gives segfault with swig4

### ISSUE THREAD

**Issue by mikand** [pysmt/pysmt#682]
I just (painfully) discovered that with swig 4.0.0 and 4.0.1 we get a segfault in the `repycudd` wrapper for BDD. The issue is in swig itself and has been fixed in swig 4.0.2.

Unfortunately, Ubuntu 20.04 is currently stuck at swig 4.0.1, but an easy workaround is to use swig 3: `apt-install swig3.0`.

**Comment by marcogario** [comment]
Thanks for reporting this. I think there isn't much we can do here, unless you want to add a check in the installer for the swig version. As Ubuntu 20.04 shipts with a problematic version, maybe a warning in the installer would be useful.

**Comment by mikand** [comment]
Agreed, the only thing we can offer (mostly to Ubuntu users) is the small fix in bb31e91 : we warn the user and switch to the `swig3.0` command that in Ubuntu 20.04 is the name for Swig version 3 (if installed).
