### ISSUE TITLE
Error installing pysmt

### ISSUE THREAD

**Issue by HeyItsBethany3** [pysmt/pysmt#686]
Hi, 

I'm struggling to install pysmt following your Readme. Running `pip install pysmt` and `pysmt-install --z3` does not install the solver. `pysmt-install --check` returns False and Not In Pythons Path. 
Is this todo with PYTHONPATH and do you know how to add the correct Path? 

Thanks so much for your help, 
Bethany

**Comment by marcogario** [comment]
What OS are you running on? Do you get any output when running `pysmt-install --z3`? Does any of the other solvers work?
From https://github.com/pysmt/pysmt/issues/288#issuecomment-798282440, it seems that you do not even get an `~/.smtsolvers` folder. Is that correct?

**Comment by HeyItsBethany3** [comment]
I'm using mac. I don't think any of the other solvers work (at least not `msat` or `cvc4`). I do get an `~/.smtsolvers` folder with a `z3` folder, but it is empty.



The output is this:

`This script allows you to install the solvers supported by pySMT.

By executing this script, you confirm that you have read and agreed
with the licenses of each solver.

Notice: the installation process might require building tools
        (e.g., make and gcc).

Continue? [Y]es/[N]o: yes`

**Comment by mikand** [comment]
Dear @HeyItsBethany3,

our continuous integration runs on OSX 10.15 (see: https://dev.azure.com/micheliandrea/PySMT/_build/results?buildId=622&view=results) and the supported solvers are: `msat`, `yices` and `z3`, however some tools need to be installed on the system (and `pysmt-install` does not currently check for those to be installed.)

We use `brew` and for OSX we install the following:
`brew install gmp gperf swig `
In addition, we need a working C/C++ compiler to be installed, i.e. you need to install `xcode`. 

However none of these prerequisites are needed for Z3 so it is strange that you do not get it installed.

Two questions for you:
1. After the output you pasted in the previous answer is there anything else on the terminal?
2. Can you try with `msat` or `yices` after installing the needed prerequisites above.

**Comment by mikand** [comment]
@HeyItsBethany3 maybe there is a simpler problem: when `pysmt-install` asks  `Continue? [Y]es/[N]o: yes` you should type just `y` not `yes` to make the installation begins. (Just pointing it out, maybe the problem is elsewhere...)

**Comment by HeyItsBethany3** [comment]
Thanks so much, this was the issue! Sorry for so much trouble!

**Comment by mikand** [comment]
@HeyItsBethany3 Excellent!

@marcogario I think we should improve the CLI of `pysmt-install`... I'll open another issue for this.
