### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [pysmt/pysmt#693]
It would be very helpful if you could tag releases (incl. `.devX`). This would enable distributions who want to run your tests to fetch the source from GitHub instead of Pypi, where only wheels are available for `.devX`.

Thanks

**Comment by marcogario** [comment]
Fabian, thanks for the feedback. The dev versions are released after every push on master. I'd prefer not to start tagging them as they do not identify any meaningful version. Proper releases are tagged.

Is the problem about being able to run the tests for a given version, or about rebuilding the package outside from pypi?

If the former, I wonder if you can use the wheel directly. We do ship the tests with the wheel. Alternatively, I think we could start uploading a src archive to pypi (in addition to the wheel).
