### ISSUE TITLE
Make FormulaContextualizer singleton in env

### ISSUE THREAD

**Issue by EnricoMagnago** [pysmt/pysmt#696]
I use multiple pysmt environment and move FNode instances from one to the other.
I noticed that at the moment a new instance of FormulaContextualizer is created in each `normalize` call on the FormulaManager.
  
I see no reason why someone would want to have multiple instances of FormulaContextualizer in the same Environment and
making FormulaContextualizer a singleton for each Environment instance would improve the usage of the internal caching done by DagWalker.

This could result in an increase of memory usage since we would have an additional cache of FNode for every environment.

The cache would potentially contain FNode coming from different environments.    
At the moment such formulae might end up in the same `__hash__`, in such cases we would evaluate the equality (identity) which should be false for any two FNode instances of 2 different environments.

**Comment by EnricoMagnago** [comment]
@mikand , @marcogario please let me know if this makes sense for you.
If so I can apply the required changes;
we could make it a singleton in the Environment itself or within the FormulaManager. Any preferences in this respect?

**Comment by mikand** [comment]
@EnricoMagnago Thanks for this analysis. Indeed, I think this can be optimized by having the `FormulaContextualizer` as a lazily initialized field of `FormulaManager` without any negative impact. If you have time, can you make a PR?
