### ISSUE TITLE
No Solver is available

### ISSUE THREAD

**Issue by UnReAlKiNg** [pysmt/pysmt#704]
I installed by using "pip install pysmt"

when i try to run a sample code
`from pysmt.shortcuts import Symbol, And, GE, LT, Plus, Equals, Int, get_model
from pysmt.typing import INT

hello = [Symbol(s, INT) for s in "hello"]
world = [Symbol(s, INT) for s in "world"]
letters = set(hello+world)
domains = And([And(GE(l, Int(1)),
                   LT(l, Int(10))) for l in letters])

sum_hello = Plus(hello) # n-ary operators can take lists
sum_world = Plus(world) # as arguments
problem = And(Equals(sum_hello, sum_world),
              Equals(sum_hello, Int(25)))
formula = And(domains, problem)

print("Serialization of the formula:")
print(formula)

model = get_model(formula)
if model:
  print(model)
else:
  print("No solution found")`
and in console i got:
`pysmt.exceptions.NoSolverAvailableError: No Solver is available`
How can i fix it?

**Comment by marcogario** [comment]
The README (in the [Installation](https://github.com/pysmt/pysmt#installation) section) includes a few steps to take for installing the solvers. Have you gone through them? If so, did any one error?
