### ISSUE TITLE
Is Linear Integer Arithmetic (LIA) supported?

### ISSUE THREAD

**Issue by jparsert** [pysmt/pysmt#715]
The README does not specifically mention LIA although I would imagine this is supported.

**Comment by mikand** [comment]
Hi!

Yes, `QF_LIA` is supported (and it is mentioned in the Readme: https://github.com/pysmt/pysmt#solvers-support)

**Comment by jparsert** [comment]
ah thanks, I was only looking at https://github.com/pysmt/pysmt#supported-theories-and-solvers
