### ISSUE TITLE
Question about evaluate-command in pysmt/smtlib/script.py

### ISSUE THREAD

**Issue by alxxalx** [pysmt/pysmt#716]
Hello, I am currently working on a scientific project regarding PySMT and I have a question about SMT-Lib Parsing and a specific method. I have written a code to parse a String which includes some functions in SMT-Lib format. After that I want to evaluate this script. Here is my simple code I want to run:

from pysmt.smtlib.script import *
from pysmt.smtlib.parser import *
from six.moves import cStringIO

smtlib = """
(declare-fun a () Int)
(declare-fun b () Int)
(assert (> (+ a b) 4))
(assert (< b (* 2 a)))
(check-sat)
(get-model)
"""

parser = SmtLibParser()
script = parser.get_script(cStringIO(smtlib))

Now I want to evaluate this script, with the method: "evaluate(solver)" which you can find in pysmt/smtlib/script.py 
(i. e. "log = script.evaluate(solver)"). But here is my question: What kind of solver that this method needs do I need to initialize? I have tried many types of solver and searched in the source code, but I couldnt find any that are fitting- except for the following one. In pysmt/solvers/smtlib.py there is a class called "SmtLibSolver", which includes methods like "declare-fun" that are required for the "evaluate" method in script.py.
But none of these methods are implemented. Is this class the right class to execute the "evaluate"-method or is there any other? If this is right, isnt it possible to use the "evaluate" method?

**Comment by marcogario** [comment]
:wave: I am not sure what you are trying to achieve, so I will leave a few pointers:
1. I believe all (SMT) solvers are defined by including the `SmtLibBasicSolver` mixin. See [msat as an example](https://github.com/pysmt/pysmt/blob/714b6b14b14abc8f0c82e6a82185c6df8cc2927a/pysmt/solvers/msat.py#L172:L173) 
   * In your example `log = script.evaluate(Solver(name='msat'))` should work.
   * However, there are limitations as the `SmtLibBasicSolver` only considers a limited set of commands. See the [definition of the mixin](https://github.com/pysmt/pysmt/blob/714b6b14b14abc8f0c82e6a82185c6df8cc2927a/pysmt/solvers/smtlib.py#L295).
2. If you have the script and you only care about the formula defined there, you can use `script.get_last_formula`
3. If you want to introduce new commands, you might want to look into this example: https://github.com/pysmt/pysmt/blob/master/examples/smtlib.py  

Hope this helps!

**Comment by alxxalx** [comment]
Thank you very much for these quick responses! It helped me, that was what I was searching for :)

**Comment by YikeZhou** [comment]
Hi all, I had a similar problem.

I tried the example code kindly provided by @mikand (with its output listed below). I wonder why some commands, for example, `declare-fun`, return `None` instead of pysmt objects. You see, I am expecting something like `Symbol('a', FunctionType(INT, []))`. Could this be a feature to be done in the future? Or is it because I misunderstood your intention? Please forgive me if so since I am quite new to this. Thanks in advance!

```
-> declare-fun returned:
None

-> declare-fun returned:
None

-> assert returned:
None

-> assert returned:
None

-> check-sat returned:
True

-> get-model returned:
b := 3
a := 2
```

**Comment by mikand** [comment]
@YikeZhou we could have done as you suggest. The current implementation reflects what a solver would with SMTLib [1]: declare* and assert are "void functions" (more precisely, they only print "success").

Changing the signature of our "evaluate" to return the pysmt objects should be easy and should not break much code, but I am not sure about the use-case. Do you have something in mind?

[1] https://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2021-05-12.pdf

**Comment by YikeZhou** [comment]
@mikand Thank you so much! Now I'm convinced that `None` is the most reasonable value to receive.

For me, I tried to read some definitions (sorts, interpreted or uninterpreted functions, etc) from a .smt2 file and then construct an assertion with them. It feels tedious and awkward to build up strings in SMT-LIB format in Python. Guess I can make use of `args` in `SmtLibCommand` to build a "function" object I need.
