### ISSUE TITLE
The "bvxnor" operator seems to be misdefined

### ISSUE THREAD

**Issue by YikeZhou** [pysmt/pysmt#747]
Hi, I've been using PySMT for quite a while and it is really helpful!
Recently I ran into a little tricky situation. Any response from you would be appreciated!

Please consider this expression: `(bvxnor #x0 #x0)`

Here is my program using **PySMT** to calculate its value:
```python
from pysmt.shortcuts import simplify, BVZero

a, b = BVZero(4), BVZero(4)
print(simplify(a.BVXnor(b)))
```
With `PySMT==0.9.5` installed, I got `0_4`.

When I tried to evaluate it with **Z3**, I got `#xf` instead.
```sh
$ z3 -in
(simplify (bvxnor #x0 #x0))
#xf
```

I guess it is the definition of `BVXnor()` in `formula.py` that leads to the discrepancy.

https://github.com/pysmt/pysmt/blob/a9e4c7117cb78dbbad1372085880f4f7c3232412/pysmt/formula.py#L894-L897

You see, the [definition of **XNOR** in Wikipedia](https://en.wikipedia.org/wiki/XNOR_gate) is like this. ⬇️ It seems that the `BVXnor()` implemented in PySMT is not a "bitwise XNOR".

|   | 0 | 1 |
|---|---|---|
| 0 | 1 | 0 |
| 1 | 0 | 1 |

So, maybe an update on this (though it is hardly used)? p.s. I would like to help with that!

**Comment by mikand** [comment]
@YikeZhou thank you so much for the detailed report. I think you are 100% correct and the implementation of the simpliication is plain wrong.

If you can make a PR to fix this it would be awesome! Otherwise, let me know and I''l try to fix this myself.
