### ISSUE TITLE
Your thought about Integration to IDE.

### ISSUE THREAD

**Issue by PorcoRosso85** [pysmt/pysmt#749]
https://news.ycombinator.com/item?id=28263501
https://adsharma.github.io/pysmt/
then, I'm here.

As you wrote, I also check [CrossHair](https://github.com/pschanely/CrossHair/raw/main/doc/source/duplicate_list.gif) and found this.
![image](https://user-images.githubusercontent.com/40359643/221851094-30cc98f9-22fa-4133-97f6-93221a9f9829.png)

I am convinced by what you said in your blog, so if you are ready to integrate pysmt, such as LSP ( language server protocol ) , I would like to know how to achieve this image-like effect.
On the other hand, if you are not ready for this integration, I would like to hear your thoughts on whether or not you are thinking of integrating in the future.

**Comment by PorcoRosso85** [comment]
This thread is not for offering to create official IDE plugin etc.
This app already has had appropreate API I think, so IDE plugin creater may create one

**Comment by mikand** [comment]
@PorcoRosso85 Please note that https://adsharma.github.io/pysmt/ is not affiliated in any way with me and @marcogario who are the authors of pysmt. 

The blog entry makes a striking confusion between pysmt (and the z3 api) and a contract language for software verification: pysmt is *not* a software contract verifier, we provide a common interface for invoking SMT solvers (on top of which you can construct software verification algorithms among other things). 

Hence, we have no intention of providing any kind of IDE integration for pysmt, let alone a contract language.
