### ISSUE TITLE
The imp module is removed in Python 3.12

### ISSUE THREAD

**Issue by dvzrv** [pysmt/pysmt#769]
Hi! :wave: 

We're currently preparing packages for upgrading to Python 3.12 on Arch Linux.

This project unfortunately uses the undocumented `imp.load_dynamic()` function:

https://github.com/pysmt/pysmt/blob/f7b599c228ee8b429aab1b82ddf167bd956ea8a3/pysmt/smtlib/parser/__init__.py#L101

With Python 3.12 the entire imp module has been removed. There is no replacement for `imp.load_dynamic()`:
https://docs.python.org/dev/whatsnew/3.12.html#imp

**Comment by marcogario** [comment]
Thank you for the heads up!

@mikand It seems the whole reason we are using `imp.load_dynamic` is to avoid having a verbatim copy of the parser (according to this [comment](https://github.com/pysmt/pysmt/blob/f7b599c228ee8b429aab1b82ddf167bd956ea8a3/pysmt/smtlib/parser/__init__.py#L59)).
As we have not made changes to the parser in a long time, shall we just make a copy and simplify all of that? If we do, I'd then suggest we add a CI check for checking the equality of those two files.

This might remove some unnecessary complexity and be an easier fix than trying to re-implement a similar logic.
WDYT?

**Comment by dvzrv** [comment]
Thanks for getting back to this issue so quickly!
A near term resolution would be awesome, as otherwise this project will be broken on Arch Linux once we upgrade. :bow: 

(cc @anthraxx for package maintainer reference)

**Comment by mikand** [comment]
@alvalentini do you have time for a quick pr on this?

**Comment by cybaol** [comment]
Replace
```python
mod = imp.load_dynamic(name, so_path)
```
with
```python
spec = importlib.util.spec_from_file_location(name, so_path)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
```
Generated by ChatGPT.
