### ISSUE TITLE
Failing Yices test (probably due to finite precision representation)

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#77]
test_solving.py:do_model (added in branch bitvector_support) fails. The reason seems to be that the variables are assigned a value that is not precise enough:

```
Traceback (most recent call last):
  File "/home/viashino/pySMT/github/pysmt/test/__init__.py", line 88, in wrapper
    return test_fun(*args, **kwargs)
  File "/home/viashino/pySMT/github/pysmt/test/test_solving.py", line 215, in test_model_yices
    self.do_model("yices")
  File "/home/viashino/pySMT/github/pysmt/test/test_solving.py", line 187, in do_model
    self.assertEqual(simp, TRUE(), "%s -- %s" % (f, subs))
AssertionError: (((r + s) = 28/5) & (s < r)) -- {r: 4278419646001971/1125899906842624, s: 2026619832316723/1125899906842624}
```

The assertion error shows a formula and an assignment. The assignment should make the formula true, but this is not the case. Indeed s+r ~ 5.5998  instead of 28/5.

We can remove the test, but it would be nice to find a proper way of handling this.

**Comment by mikand** [comment]
#78 addresses this issue. It is still impossible (due to pyices limitations) to have arbitrary-precision using yices, but now rational numbers are hadled as a pair of two 64-bit integers.

A complete solution would be to write a custom yices wrapper that uses libgmp.

**Comment by marcogario** [comment]
Fixed for now. See #79 for future improvements.
