### ISSUE TITLE
floating points are not printed as floating points

### ISSUE THREAD

**Issue by MikolasJanota** [pysmt/pysmt#778]
From the following code, I'm getting `(* 1.0 (/ 1 4))`.  This makes it difficult for external tools. For instance, vampire refuses to parse ints in place of reals.

```
  from pysmt.shortcuts import Div, Real
  print(Div(Real(1), Real(4)).to_smtlib(daggify=False))
```

**Comment by mikand** [comment]
Hi @MikolasJanota,

thanks for the report. We never noticed this because most SMT parsers work without issues. Nonetheless, I prepared a simple fix in #779. Can you try if this works for you?
