### ISSUE TITLE
Not informative assertion for unsupported operators

### ISSUE THREAD

**Issue by muverigno** [pysmt/pysmt#80]
The following code raises the exception "NotImplementedError", because the quantifier is not handled by the default logic.
I would excpect a better error reporting, e.g. "Not supported logic"

from pysmt.shortcuts import *
from pysmt.typing import BOOL
solver = Solver()
xs = Symbol("xs",BOOL)
solver.add_assertion(Exists([xs],xs))

**Comment by marcogario** [comment]
This happens because the selected solver does not support the Exists operator. 
We should:
- Catch walk_error exceptions in the converter and raise a more meaningful exception
- (Optionally) Catch conversion error exceptions in add_assertion, and suggest to the user to specify a logic.

**Comment by marcogario** [comment]
To properly support this, should consider introducing a new exception: UnsupportedNodeType, that carries around the node type information. This should be the default error in walk_error (instead of the generic NotImplementedError)

**Comment by marcogario** [comment]
PR #130
