### ISSUE TITLE
BDD ordering support

### ISSUE THREAD

**Issue by mikand** [pysmt/pysmt#89]
We shall consider adding support for static BDD ordering specification as well as dynamic reordering.
@cmattarei could be interested in this feature.

**Comment by mikand** [comment]
From a preliminary analysis it seems that is sufficient to use ```NewVarAtLevel``` instead of ```NewVar``` in order to create variables in a pre-determined order. Otherwise variables are appended at the bottom. An alternative possibility is to pre-create all the variables in the desired order.

**Comment by mikand** [comment]
56c8ec0d73483 gives a first shot at this issue.

**Comment by marcogario** [comment]
PR #100
