### ISSUE TITLE
Possible race conditions in Continuous Integration

### ISSUE THREAD

**Issue by mikand** [pysmt/pysmt#93]
Recently, I noticed that shippable.com has some trouble with our tests.

In configurations where no solvers are available, the tests are failing because a SMT-Lib wrapper solver is not found. This seems to me a sort of race condition or a caching problem in our CI.

E.g. https://app.shippable.com/builds/5548786542da970c000f1c6f

**Comment by marcogario** [comment]
Is this still happening after disabling paralell runs?
