### ISSUE TITLE
feature request: support for get_implicant()

### ISSUE THREAD

**Issue by agriggio** [pysmt/pysmt#94]
It would be nice to have a `get_implicant(f)` function, that returns an
SMT-level implicant for a satisfiable formula `f` (aka a T-consistent truth
assignment for the atoms of `f`, aka a "propositional" model that is
T-consistent).
Alternatively, what's the easiest way of achieving this?

**Comment by mikand** [comment]
This should be what you are looking for.

```python
def get_implicant(formula, solver_name=None,
                  logic=None, complete=False):
    model = get_model(formula, solver_name=solver_name, logic=logic)
    if model is None:
        return None
    else:
        def assignment_as_formula(var, val):
            if val.is_true():
                return var
            elif val.is_false():
                return Not(var)
            else:
                return Equals(var, val)

        if complete:
            return And(assignment_as_formula(x, model.get_value(x))
                       for x in formula.get_free_variables())
        else:
            # Partial model -> more general implicant
            return And(assignment_as_formula(x, v) for x,v in model)
```

**Comment by mikand** [comment]
I opened a pull request #95 for a proper implementation of ```get_implicant``` in pysmt.

**Comment by mikand** [comment]
@agriggio I just realized that this might not be what you were looking for... 
for a formula like ```( x | y ) & (a < 14 | a > 18)``` what is a possible "implicant"?

**Comment by agriggio** [comment]
Yes, the above is not what I want :-)
For the example, a (prime) implicant would be `x & (a < 14)`, or a (non-prime) one `x & !y & (a > 18) & !(a < 14)`

**Comment by marcogario** [comment]
PR #109
